### ISSUE TITLE
Advice needed: "stack level too deep"

### ISSUE THREAD

**Issue by zverok** [lsegal/yard#1002]
Hey.

While trying to document really large codebase, I stuck with
```
yard-0.9.5/lib/yard/parser/ruby/ast_node.rb:198:in `children': stack level too deep (SystemStackError)
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/parser/ruby/ruby_parser.rb:650:in `freeze_tree'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/parser/ruby/ruby_parser.rb:652:in `block in freeze_tree'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/parser/ruby/ruby_parser.rb:650:in `each'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/parser/ruby/ruby_parser.rb:650:in `freeze_tree'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/parser/ruby/ruby_parser.rb:652:in `block in freeze_tree'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/parser/ruby/ruby_parser.rb:650:in `each'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/parser/ruby/ruby_parser.rb:650:in `freeze_tree'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/parser/ruby/ruby_parser.rb:652:in `block in freeze_tree'
	 ... 10163 levels...
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/bin/yardoc:23:in `load'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/bin/yardoc:23:in `<main>'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

Unfortunately, codebase belongs to proprietary project, so I can't share it. Neither I can narrow the case (to current moment). I turned on `--debug` option to see the filename on error, and there is nothing special in this file. Moreover, when I comment it out, the very same error emerges in the next file (and if I comment out that one, in the next, and so on).

What can I do for debugging/understanding? Is that possible that size of codebase could be a limitation/fatal problem for YARD?..

**Comment by zverok** [comment]
(YARD is 0.9.5, Ruby is 2.3.1)

**Comment by MSP-Greg** [comment]
I have not communicated with Loren about this, but previously, I've had to change re-entrant Ruby code to 'stack based' code (can't recall the academic name for it).

Below is a patch, I've ripped some docs with it, and it passes the RSpec tests.

In the file listed in your error output `ruby_parser.rb`, at the bottom of the file, rename the method `freeze_tree` to something like `freeze_tree_no`, and add the following code:

```ruby
        def freeze_tree(node = nil)
          t2_nodes = []
          t2_nodes.push(node || root)
          while !t2_nodes.empty? do
            p_node = t2_nodes.shift
            p_node.children.each { |child| child.parent = p_node }
            t2_nodes += p_node.children
          end
        end
```

Please let us know if it works.

**Comment by zverok** [comment]
@MSP-Greg It just led me to:
```
/media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/docstring_parser.rb:282:in `block in call_after_parse_callbacks': stack level too deep (SystemStackError)
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/docstring_parser.rb:281:in `each'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/docstring_parser.rb:281:in `call_after_parse_callbacks'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/docstring_parser.rb:190:in `post_process'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/docstring_parser.rb:120:in `parse'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/handlers/base.rb:451:in `register_docstring'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/handlers/base.rb:412:in `block in register'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/handlers/base.rb:405:in `each'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/gems/yard-0.9.5/lib/yard/handlers/base.rb:405:in `register'
	 ... 10158 levels...
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/bin/yardoc:23:in `load'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/bin/yardoc:23:in `<main>'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /media/storage/home/zverok/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

:(

**Comment by MSP-Greg** [comment]
Just checking, are you using any plugins or loading anything in your .yardopts file?

**Comment by MSP-Greg** [comment]
BTW, you mentioned 'really large' codebase. I've used YARD for Rails, Ruby itself, and the AWS SDK (much of which is not Ruby code).  Regardless, I'll see what I can find.

**Comment by zverok** [comment]
My .yardopts:
```
--markup=markdown
--markup-provider=redcarpet
--load ./lib/support/yard/handlers.rb
app
apq
lib
```

...and `./lib/support/yard/handlers.rb` is (as per https://github.com/lsegal/yard/issues/994):
```ruby
class MemoizeHandler < YARD::Handlers::Ruby::Base
  include YARD::Handlers::Ruby::DecoratorHandlerMethods
  handles method_call(:memoize)
  namespace_only

  process do
    case statement.type
    when :fcall, :command
      process_decorator
    end
  end
end
```

Nothing more is used, as far as I can understand our large codebase.

**Comment by zverok** [comment]
> BTW, you mentioned 'really large' codebase. I've used YARD for Rails, Ruby itself, and the AWS SDK (much of which is not Ruby code). Regardless, I'll see what I can find.

```ruby
Dir['{app,apq,lib}/**/*.rb'].count
# => 2075 
```
I'm not sure whether it should be considered large or moderate.

**Comment by MSP-Greg** [comment]
Victor,

I think we can call 2,075 files 'large'. Probably a few methods.  Anyway, this is definitely not a recommended patch, because I ran YARD with it, and it didn't call a block from `call_after_parse_callbacks`.  Said another way, I have no code to test it against.

It does pass the RSpec tests.  The following at least prevents one of the callback blocks from calling itself again from `call_after_parse_callbacks`, if its using the same instance of `DocstringParser`, which I am not sure about.

In `docstring_parser.rb`, rename `call_after_parse_callbacks`, and substitute the following:

```ruby
    def call_after_parse_callbacks
      t2_apcb = self.class.after_parse_callbacks.uniq
      return if t2_apcb.empty?
      @after_parse_callbacks = nil
      t2_apcb.each { |cb| cb.call(self) }
    end
```

I have no idea what kind of output you'll get, in particular whether some of these methods may have issues with their docstrings (documentation from comments) or their tags.

I'm not sure if Loren was posting a complete example or just pointing you in the right direction in his reply in #994.

Greg

**Comment by lsegal** [comment]
@zverok have you tried disabling the handler that you loaded and re-running to confirm if the issue is coming from YARD itself?

**Comment by zverok** [comment]
@lsegal tried it, didn't change anything. @MSP-Greg your suggestion didn't change anything, too :(

**Comment by lsegal** [comment]
@zverok unfortunately at this point we would need some form of minimal reproduction case. If you look at your `--debug` output you should be able to see which file was last processed before the exception occurred. I would recommend re-running YARD on just that file to see if it happens again (`yard doc path/to/file.rb`). If it does, try to narrow down the minimal code in that file that causes the exception and post the results here.

**Comment by zverok** [comment]
@lsegal No, it is not reproduced on one file. Moreover, it even not reproduced on entire large `apq` folder (we have two equally large `app` and `apq` folders, and third, smaller `lib`). Only when both `app` and `apq` are processed. I vaguely suppose it could be something regarding names resolution in large codebase? (We have many classes with same names, but in different namespaces.)

Also, as I've said previously, if I comment out / remove last parsed file, the problem repeats with next one, and the next and so on.

**Comment by lsegal** [comment]
@zverok try running multiple YARD commands instead of a single one:

```sh
$ yard doc app
$ yard doc -c apq
$ yard doc -c lib
```

This *may* cause rendering issues, but it should confirm whether this is related to some kind of object resolution.

**Comment by zverok** [comment]
> try running multiple YARD commands instead of a single one:

OK, this one was ended without any errors. What conclusion it leads us to?.. :)

**Comment by MSP-Greg** [comment]
@zverok Victor,

Glad things are moving along.  Just checking, do you have the two patches in place, or did you remove/comment them out?

**Comment by zverok** [comment]
@MSP-Greg currently they are both in place. (If it is necessary, I can try to remove them and re-try everything.)

PS: I should say I'm not afraid of reading large codebases, neither debugging them (I'm pretty experienced Rubyist), I just need some advices what are places I should start to look at: YARD is a complicated masterpiece, and to that day I have no occasion to look inside its code.

**Comment by MSP-Greg** [comment]
@zverok I would definitely try with (I think you already tested 'with') and without.  Just flip the names.

I don't know about the second patch (`call_after_parse_callbacks`), but the patch to `freeze_tree` may help with very deep parsing structures.

I've run into Ruby re-entrant issues before while parsing **big** 3D models with heavily nested components.  The 'stack/list' based algorithm fixes it.

**Comment by lsegal** [comment]
@zverok I believe there are two major possibilities in what's happening, with differing workarounds: 

1) YARD recurses every time it attempts to resolve a namespace that is out of order (not yet defined when used). If a codebase causes YARD to continually go back and forth resolving unseen namespaces, you will be doubling your stack size each time. In a large codebase, that shouldn't take too many namespace resolution errors to eventually blow the stack. Unfortunately there's no other way to implement this (we previously used continuations, but they are poorly supported across platforms). Fortunately you should be able to quickly determine if this is happening by reading `--debug` output logs to see if you read a lot of the following error:

```
[debug]: Missing object B in file `lib/mylib/a.rb', moving it to the back of the line.
```

Following Ruby's file naming conventions usually resolves most of these errors automatically (since child classes are placed in subdirectories of the parent's declaration file, e.g., `a.rb`, `a/b.rb`), but if you are seeing this, you can modify your `.yardopts` to explicitly list a sorted file list that reduces the amount of namespace issues during parsing. Specifically, if you see something like the missing `B` object inside `a.rb` in the above example, you would add the following to your .yardopts:

```
lib/mylib/b.rb
lib/**/*.rb
```

The above will process B first. Now this causes more problems if B relies on something else, but at the very least you can minimize the amount of re-processing by providing the best ordered list of files possible.

2) If the above is *not* happening, my guess is that your codebase really is too large for YARD to parse. This is the first time I've seen such a case. Your workaround in this case is to use the 3 command combo provided above, to split up the parsing.

Unfortunately it's hard to immediately know which is happening. If we had the `yard --debug` output that would be really helpful in determining when the error is happening and what state YARD might be in. You can scrub file and class names if you want (though if you do this, they should continue to be uniquely identifiable), but can you provide the output?

You may also want to try downgrading YARD to an earlier version to see if there might have been some regression / change introduce that caused the error. Was YARD ever working on this codebase before?

@MSP-Greg this is unrelated, but can you push your stack patch on freeze_tree back upstream as a PR (and any other modifications you've made to your YARD fork)-- assuming tests are passing?

**Comment by MSP-Greg** [comment]
@lsegal I haven't come across the stack issue in YARD before, the stack patch was a result of seeing this issue.

Since I've got the open PR on master and browser. I'll submit the stack patch on stack_patch branch.

Re my other code changes, most of them are inside yard-t2.  Some, you've made changes to YARD since 0.8.7.6.  On my TODO list is reviewing what mods I can remove due to changes you've made in YARD and what mods could move into YARD, but I'm still moving things around and refactoring in t2.

In general, I would prefer t2 to just affect code after parsing is finished.  As I believe I've mentioned before, I've got things like the attribute / alias changes I've made, which could be moved into YARD, but might  require some re-writing to do so.  Hence, if they're working in t2, I'm not going to rewrite and test them in YARD unless you express an interest in my doing so.

**Comment by lsegal** [comment]
@MSP-Greg if you have fixes that are unspecific to yard-t2 and are useful for general usage, I'd love to have them in YARD-- at the very least, I'd love to see what fixes are being made.

**Comment by zverok** [comment]
> I believe there are two major possibilities in what's happening, with differing workarounds:

> 1) YARD recurses every time it attempts to resolve a namespace that is out of order (not yet defined when used). If a codebase causes YARD to continually go back and forth resolving unseen namespaces, you will be doubling your stack size each time. In a large codebase, that shouldn't take too many namespace resolution errors to eventually blow the stack. Unfortunately there's no other way to implement this (we previously used continuations, but they are poorly supported across platforms). Fortunately you should be able to quickly determine if this is happening by reading --debug output logs to see if you read a lot of the following error:

```
[debug]: Missing object B in file `lib/mylib/a.rb', moving it to the back of the line.
```

Yeah, it seems to be the case. I see a ton of those messages. In our `apq/` folder we have myriad of `class Namespace1::Namespace2::ClassName`, with `Namespace1` and `Namespace2` never seen to be defined on themselves (and all of it works because of Rails constant lookup magic, I believe).

Thanks, we'll try to investigate the matters!

**Comment by MSP-Greg** [comment]
@zverok
> Yeah, it seems to be the case. I see a ton of those messages. In our apq/ folder we have myriad of class `Namespace1::Namespace2::ClassName`, with `Namespace1` and `Namespace2` never seen to be defined on themselves (and all of it works because of Rails constant lookup magic, I believe).

This kind of situation of occurs when project's subclass objects brought in via `require` statements, which is common (and done in YARD) with server related objects.  The `@!parse` tag will allow you to add comments like (I've done it before, but all the code is gone, check syntax):

`@!parse module Namespace1 end`
`@!parse module Namespace1::Namespace2 end`

which create the objects in YARD's data store, and also shows the containership structure in the 'Class List'.

No idea how many definitions you'd need to add via `@!parse`, but this is a possible (and existing YARD) solution.

**Comment by zverok** [comment]
@MSP-Greg thanks! Sounds reasonable, forgot about `@!parse` tag. Don't know though whether it is better to imitate proper module definitions than define them actually properly :)

**Comment by zverok** [comment]
Managed to fix it with proper namespacing introduced. Thanks @MSP-Greg @lsegal

**Comment by jmthomas** [comment]
I had a simple typo like the following which also produced this 'stack level too deep' error:
```
class MyClass
  # @param (see MyClass#my_method)
  def my_method(value)
  end
end
```
Will this patch address this type of stupid recursion mistake?

**Comment by MSP-Greg** [comment]
@jmthomas Have you tried with a version after this patch?  I tried the following:

```ruby
class MyClass
  # @param (see MyClass#my_method)
  def my_method(value)
  end

  # @param (see MyClass#my_method2)
  def my_method1(value)
  end

  # @param value [String]
  def my_method2(value)
  end
end
```
And everything doc'd as expected.  YARD shows the following error:
```
Detected circular reference tag in `MyClass#my_method', ignoring all reference tags for this object  @param).
```

**Comment by jmthomas** [comment]
It doesn't look like there's been a release since you patched. I'll take your word for it and wait for the release. Thanks for the patch!

**Comment by MSP-Greg** [comment]
@jmthomas Sorry, you're correct.  I've got my YARD gem folders linked to my YARD git folders, so I'm always running on code from the master branch.  I do that with a few gems...

Your issue isn't affected by this patch.

@lsegal fixed it in [Detect and log error for circular reference tags](https://github.com/lsegal/yard/commit/070baa2463b88f790099ccf070ad1e5173952f10)

Also see #1011.

**Comment by jmthomas** [comment]
Looks like a lot of good patches have been applied since Jul 22. I'd love a new release whenever @lsegal has an opportunity as both these issues will crash YARD and are pretty confusing to noobs. Thanks again for looking into this.

**Comment by jdickey** [comment]
Hi, folks. I'm still running into this with v0.9.12, particularly in relation to Version 2.7.0 of the `mail` Gem, where I mistakenly opened mikel/mail#1211. This issue's marked as closed, but the behaviour is still depressingly repeatable. Guidance?

Quoting mikel/mail#1211:

----

Gem version 2.7.0 as installed from rubygems.org
Ruby version 2.5.0 on Debian Jessie. Replicated on OS X 10.11.6, also with MRI Ruby 2.5.0

## Observed behaviour

```
$ gem install mail -v 2.7.0
Fetching: mail-2.7.0.gem (100%)
Successfully installed mail-2.7.0
Building YARD (yri) index for mail-2.7.0...
/usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/ruby/ast_node.rb:212:in `block in traverse': stack level too deep (SystemStackError)
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/ruby/ast_node.rb:210:in `each'
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/ruby/ast_node.rb:210:in `with_index'
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/ruby/ast_node.rb:210:in `traverse'
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/ruby/ruby_parser.rb:601:in `insert_comments'
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/ruby/ruby_parser.rb:60:in `parse'
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/ruby/ruby_parser.rb:17:in `parse'
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/source_parser.rb:442:in `parse'
	from /usr/local/bundle/gems/yard-0.9.12/lib/yard/parser/source_parser.rb:46:in `block in parse'
	 ... 30 levels...
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/command_manager.rb:171:in `process_args'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/command_manager.rb:141:in `run'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/gem_runner.rb:59:in `run'
	from /usr/local/bin/gem:21:in `<main>'
$
```

## Expected behaviour

```
gem install mail -v 2.7.0
Fetching: mail-2.7.0.gem (100%)
Successfully installed mail-2.7.0
Building YARD (yri) index for mail-2.7.0...
Done installing documentation for mail after 0 seconds
1 gem installed
$
```

**Comment by zverok** [comment]
@jdickey I believe that it is unrelated problem (e.g. better to create a new GitHub issue for it). 

The problematic file is https://github.com/mikel/mail/blob/master/lib/mail/parsers/address_lists_parser.rb, which is generated by Ragel and contains some constant spanning 30k (yes, 30 thousand) lines. Probably, YARD should fail more gracefully in such weird cases.

**Comment by MSP-Greg** [comment]
@zverok

> I believe that it is unrelated problem

Agreed.

Thanks for the file reference.  It may be a Ripper issue, I'll have a look later if Loren doesn't get to it first.

**Comment by jimmymeraki** [comment]
I'm having the same issue as OP with a very large Rails codebase (`Dir["{app,lib}/**/*.rb"].count == 5219`).

Turning debug logging on, I see the "Missing object, moving it to the back of the line" message a couple hundred times before the `SystemStackError` causes YARD to crash.

We have many, many instances of the "shorthand" module syntax (`Foo::Bar::Baz`) and rely on the Rails autoloader to create these intermediate modules at runtime. It would not be feasible for us to restructure all our code to use nested modules (nor would this be desirable as it introduces rightward drift from indentation) or to add manual `@!parse` tags everywhere to satisfy YARD. Breaking down `yard doc` into multiple runs that each operate on a subset of the codebase [as suggested above](https://github.com/lsegal/yard/issues/1002#issuecomment-236430255) does not seem scalable to me—it's only a matter of time before one of the subsets becomes too large itself and encounters the same problem.

I suspect it's common for Rails apps to rely on the autoloader for this type of module auto-vivification. I believe the Rails generators even use this pattern in generated code, e.g. the namespaced controller `Admin::ArticlesController` example in [the official guide on routing](https://guides.rubyonrails.org/routing.html#controller-namespaces-and-routing). Is there really no better way to support this in YARD? Maybe an option (probably off by default) to auto-vivify missing modules in the same way the Rails autoloader does. It could just assume an empty module, and then if/when the actual module definition is encountered, treat it as a reopening. This would have the same effect as adding the `@!parse` tags [as described above](https://github.com/lsegal/yard/issues/1002#issuecomment-236430255) without having to type them out manually in every source file.

**Comment by lsegal** [comment]
@jimmymeraki is there a reason the `.yardopts` approach does not work here?

Without knowing too much about the specific codebase but enough about Rails, I would imagine that the vast majority of your inter-file references either come from models or concerns, thus it _should_ be possible to provide those globs up front to simplify the vast majority of the NamespaceMissingErrors. The following .yardopts should help in this case:

```
app/models/concerns app/models app lib
```

Of course you would do this with whichever objects log the most out of order load warnings, so if it happens to be something other than models, I would recommend adjusting the above. You can also be specific and list exact files if it happens to be just a handful of files (though as you note that will break eventually)

If this doesn't work, you could consider writing a small extension to pre-load your intermediate namespace modules that are causing the majority of out of order warnings. You could do this by creating a Ruby script that runs alongside YARD again configured via .yardopts (add `-e path/to/script.rb` to the end or a newline) where `path/to/script.rb` is:

```ruby
require 'activesupport'

YARD::Parser::SourceParser.before_parse_list do |files, globals|
  Dir["app/{models,controllers}/**/*"].sort.select { |d| File.directory?(d) }.uniq.each do |dir|
    dir = dir.sub(%r{^app/.+?/}, '')
    YARD::CodeObjects::ModuleObject.new(:root, dir.camelize) if dir != "concerns"
  end
end
```

The above will inflect all intermediate directories in your models and controllers subfolders. You can do the same for other parts of your app if necessary.

NB: this is an _untested_ naive implementation that doesn't necessarily handle all cases but should put you on the right track to building out the extension.

I would recommend the first approach before delving into the latter. Frankly the extension approach should only be needed if you have hundreds of inter-dependent models (A -> B, B -> A) in your codebase,

Hope that helps!

**Comment by jimmymeraki** [comment]
Thank you for the suggestions!

I tried loading `app/models/concerns` and `app/models` before `app` and `lib` but the same `SystemStackError` crashed YARD after about the same amount of progress. There are so many instances of the "Missing object, moving it to the back of the line" error in our application across so many directories that I don't see a feasible way to formulate a static list for `.yardopts`, and even if I found some magical incantation that worked, it doesn't seem like it would be future proof to growth and change in our codebase.

I then tried the module preloading code you suggested. With this script, `yard doc` was able to complete successfully without the `SystemStackError` crash. However, in the HTML documentation it generated, the leaf modules/classes are completely missing. It seems that the modules that were created with this extra script remain empty, even when their child constants are eventually parsed.

For example, say there is a file at `app/foo/bar/baz.rb` that contains `module Foo::Bar::Baz; end`. This results in entries in the class list in the left sidebar of the generated HTML page for `Foo` and `Foo::Bar`, but `Foo::Bar::Baz` is absent. The documentation pages for `Foo` and `Foo::Bar` both show a gray box with the text "Defined in: (unknown)". The page for `Foo` lists `Bar` in the "Defined Under Namespace" section, but the page for `Bar` does not have that section at all, whereas I would expect it to list `Baz`.

Is there a way to use this constant preloading technique, but also merge the real modules into the preloaded modules when they are discovered during the normal parsing process?

**Comment by jimmymeraki** [comment]
After a few days of learning the YARD codebase, I came up with this patch: https://github.com/lsegal/yard/compare/main...jimmymeraki:yard:autovivify-spike

This change will automatically create modules for all parent namespaces whenever it parses a nested constant. With this patch, I was able to successfully run YARD on our code base without the stack recursion error, and without the problem of missing leaf classes/modules that happened with @lsegal's suggested script.

Questions:

1. Would the project be receptive to a PR with my patch? Obviously I would add tests, documentation, and make the behavior conditional on a config option which is disabled by default. (The implementation as written right now might not be robust enough, since I only learned enough about YARD to fix my immediate problem, and it might not be the best way to implement the solution. But if it's worth trying to upstream this, that could be discussed in the PR.)
2. If this patch wouldn't be accepted in YARD itself, is there some sort of hook that YARD exposes where I could perform the same logic in an external file loaded with `yard doc -e`? Something akin to `YARD::Parser::SourceParser.before_parse_list` but that would allow me to inject custom logic into module and class creation as I've done in the patch.
3. If there is no existing hook that would make this possible, would the project be receptive to a PR that adds such hooks? If so, any guidelines I should follow for implementation?
4. If the project won't take any sort of patch and there's no existing hooks I can use, is there any other escape hatch I can use to solve my problem? I'm really hoping not to have to resort to monkey patching or forking the project.

Thanks!

**Comment by lsegal** [comment]
> I then tried the module preloading code you suggested. With this script, yard doc was able to complete successfully without the SystemStackError crash. However, in the HTML documentation it generated, the leaf modules/classes are completely missing.

I was unable to reproduce this issue with the code provided. The following content inside `app/controllers/foo/bar/baz.rb` generated the docs screenshotted below:

```ruby
# file: app/controllers/foo/bar/baz.rb

# Docs for Baz module
module Foo::Bar::Baz
  # Does something
  def a; end
end
```

![image](https://user-images.githubusercontent.com/686/181656317-a1bc00b6-8c52-4614-848f-11420b067307.png)

Note the "controllers" directory, which was part of the requirement of the implementation above (this of course could be changed).

I do have "Defined in (unknown)", for Foo / Foo::Bar, but this is also expected based on the implementation (and the fact that these modules are not defined anywhere in source, thus is technically correct).

> Would the project be receptive to a PR with my patch? Obviously I would add tests, documentation, 

I would recommend running existing tests against your patch. My guess is they would not pass. Adding new tests would likely not be sufficient to enable the behavior if you're not addressing the many ways in which the proposed changes would break other use cases.

> If this patch wouldn't be accepted in YARD itself, is there some sort of hook that YARD exposes where I could perform the same logic in an external file loaded with yard doc -e

Here's the part where we go back to the suggested implementation above. This method is working for me and I recommend iterating on any rough edges that might cause this to fail in your codebase.

> If there is no existing hook that would make this possible, would the project be receptive to a PR that adds such hooks? 

If there wasn't already a method to make this work without a hook, this could be on the table. However, as it stands, the code provided earlier should be a completely viable path forward and should not require any new hooks to YARD.

> If the project won't take any sort of patch and there's no existing hooks I can use, is there any other escape hatch I can use to solve my problem?

See above.

**Comment by Royalflamejlh** [comment]
> This happened to me in v0.9.37 for a very large rails project. Setting a very high `RUBY_THREAD_VM_STACK_SIZE` fixed it for me.

`RUBY_THREAD_VM_STACK_SIZE=33554432 yard doc`

worked for me
