### ISSUE TITLE
Documenting rails controllers using yard

### ISSUE THREAD

**Issue by PascalTurbo** [lsegal/yard#1022]
Hi There,

For documenting rails controllers' params, it's necessary to document a @param that isn't declared in the method call. Because params is part of the controller itself. 

    class MyController < ApplicationController
      # @param [Hash] params The params from the get request
      # @option params [Boolean] :with_lovely_names Write output with lovely names
      def index
        # Do Something with params
      end
    end

    [warn]: @param tag has unknown parameter name: params 
      in file `app/controllers/my_controller.rb' near line 4

Maybe this is a feature request or there is an existing workaround I couldn't find in the documentation. 

Thank Allot

**Comment by lsegal** [comment]
There are a few things here:

1. That warning line is a warning, not an error, which means you will still get documentation for the param.
2. You can use [`@overload`s](http://www.rubydoc.info/gems/yard/file/docs/Tags.md#overload) to rewrite a method's signature.
3. But most importantly, you shouldn't be doing this. Although you're putting text in the right spots, you're not accurately documenting the API by pretending `params` is an argument to your controller method-- because it is not.

The real way to go about this is to create a custom `@tag` for your specific purpose (you can use `yard doc --tag NAME` to accomplish this, see the help). What you're actually trying to document is meta information that is not related to the programmatic Ruby API. It might be relevant to the function of the app, but it isn't a detail of your index "method" (method being a *Ruby method*).

You should ask why you are trying to document a separate hash object in your index controller action. Is this relevant to the user of the API (in a writing Ruby code context, not a visit-your-website context)? It's not information I would need to know to call `MyController.new.index`, for example. Maybe that's not entirely apt in the context of Rails, but that's really what the `@param` tag is about.

If you're trying to document this for the web users as a remote web service API type thing, then it doesn't matter that it's (a) a hash, (b) a parameter, or (c) called "params". In that context, all you have is a JSON / XML / whatever document that the user needs to send. You should document *that*-- and don't tie it to the `params` object. From the external user's perspective, it's not relevant info.

Hopefully that explains a bit. You can continue to workaround this with `@overload` but I'd recommend following the subsequent recommendations.

**Comment by franklinyu** [comment]
@PascalTurbo have a look at [yard-restful](https://github.com/kraft001/yard-restful) plugin.

**Comment by lsegal** [comment]
Closing since this was a question (with answers).
