### ISSUE TITLE
Parser goes weird on complex regexp in code

### ISSUE THREAD

**Issue by zverok** [lsegal/yard#1023]
## Steps to reproduce

Minimal code I was able to create for reproducing the issue:

``` ruby
class BaseWrapper
  def description(text)
    @object.description =
      text
      .gsub(/^[ \t]+/, '')      # remove spaces at a beginning of each line
      .gsub(/\A\n|\n\s*\Z/, '')
  end

  class PostProcessProxy
  end
end
```

What's going on after this is instead of `PostProcessProxy` there is `ostProcessProxy` in docs (and all the other entity names after problematic method is screwed this or that way).

Specifically, problem is created by those two lines:

``` ruby
      .gsub(/^[ \t]+/, '')      # remove spaces at a beginning of each line
      .gsub(/\A\n|\n\s*\Z/, '')
```

If I'll remove the second with complicated regexp -- everything becomes ok. If I remove the _comment_ from the first of them -- everything becomes ok. But in current state of those lines everything is screwed up.
## Environment details:
- OS: Ubuntu 14.04
- Ruby version (`ruby -v`): `ruby 2.2.4p230 (2015-12-16 revision 53155) [i686-linux]`
- YARD version (`yard -v`): `yard 0.9.5`

**Comment by iarkhanhelsky** [comment]
There is no problem with regex. Less code to reproduce same issue:
```ruby
class BreakParser
  def break_parser
    obj # This comment breaks all.
      .bar
  end
end

class AffectedClass
end
```

calling `yard --list` will produce:
```
yard/t.rb:1: BreakParser
yard/t.rb:2: BreakParser#break_parser
yard/t.rb:8: ffectedClass
```

No matter how many methods after `break_parser` will be inserted in `BreakParser` class. All of them will be fine. Only next class will be affected. 

The problem in `AstNode#source_range` it maps to`"ffectedClass "` (note trailing space) instead of `"AffectedClass"`. 

Issue causes totally unreadable documentation in more complex examples.

**Comment by lsegal** [comment]
Thanks for reporting-- sorry this took so long to track down!
