### ISSUE TITLE
How to specify fully-qualified object name

### ISSUE THREAD

**Issue by sh01ch1** [lsegal/yard#1029]
``` ruby
module Namespace
  class Class
    # @param klass [Class] a standard Ruby class
    def foo(klass)
      # ...
    end
  end
end
```

Yard assumes that the `klass` param's type is `Namespace::Class` and makes a link to the `Namespace::Class` page. However, I intend the type to be just the standard `Class`. Is there a way to specify a fully-qualified object name like `::Class`?

**Comment by lsegal** [comment]
Have you tried `::Class`?

**Comment by sh01ch1** [comment]
Yes. Unfortunately, a link to the `Namespace::Class` page was generated :(

**Comment by MaxPleaner** [comment]
This is a bit funny. I've come to report a similar issue, but the other way around. I have a class method `Namespace::Class.run` which I link to:

```txt
{Namespace::Class#run}
```

This shows up in the HTML like `Class#run` which isn't exactly what I want. The Namespace should be included when it's called. 

In the meantime, this is what I'm using to make it display correctly:

```txt
# To run the code, use {Namespace::Code#run Namespace::Code.run}
```
It works, but it's too verbose to be in the source code.

**Comment by lsegal** [comment]
@MaxPleaner if you link to method X from another method in the same namespace, it will use a relative path to the object (including only the class portion of the fully qualified name). In other words:

```ruby
module Namespace
  class MyClass
    def self.a; end

    # look at {#a}.
    def b; end
  end
end
```

The above link to `{#a}` will display as `MyClass.a`, never `Namespace::MyClass.a`. This is intentional and expected behavior in YARD. If you're trying to disambiguate an ambiguous class name like "ClassMethods" or something similar, unfortunately your solution listed above is the best plan-- either that, or make sure to use unambiguous class names across your modules.
