### ISSUE TITLE
Undocumentable mixins for extend / include calls

### ISSUE THREAD

**Issue by radar** [lsegal/yard#1034]
When we run `yard` inside the `i18n` codebase, it shows the warnings as shown in https://github.com/svenfuchs/i18n/issues/185.

## Steps to reproduce

Reproduced here:

```
$ yard
[warn]: in YARD::Handlers::Ruby::ExtendHandler: Undocumentable mixin: YARD::Parser::UndocumentableError for class I18n
[warn]:   in file 'lib/i18n.rb':16:

  16: extend(Module.new {

[warn]: in YARD::Handlers::Ruby::MixinHandler: Undocumentable mixin: YARD::Parser::UndocumentableError for class I18n::ExceptionHandler
[warn]:   in file 'lib/i18n/exceptions.rb':7:

  7: include Module.new {

Files:          44
Modules:        39 (   35 undocumented)
Classes:        22 (   16 undocumented)
Constants:      19 (   18 undocumented)
Methods:       127 (   61 undocumented)
 37.20% documented
```

## Actual Output

Shown above.

## Expected Output

No warnings shown.

## Environment details:

* OS: Mac OS X 10.12.1
* Ruby version (`ruby -v`): ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
* YARD version (`yard -v`): yard 0.9.5

I have read the Contributing Guide.

---

What code changes can we make within `i18n` to stop this error from happening?

**Comment by lsegal** [comment]
The warning here is valid and expected, since it is an undocumentable mixin. 

To answer your question: don't use anonymous modules if you want YARD to be able to resolve the mixin. Revert svenfuchs/i18n@c5d9e8cfbda9bdac0dd4f4231d12e5eb8a1c184e and YARD should generate correct documentation.

I am marking this as closed since YARD is behaving as expected.

**Comment by radar** [comment]
Thanks @lsegal for your time. I will do just that!
