### ISSUE TITLE
Groups are not being shown in the generated documentation

### ISSUE THREAD

**Issue by bakku** [lsegal/yard#1039]
When using `# @!group` and `#@!endgroup` the group is not shown anywhere on the generated docs page

## Steps to reproduce

1. Write some code kind similar to this:
     `# @!group Relations`
     `belongs_to :author`
     `has_many :pages`
     `# @!endgroup`
2. Run yard
3. Open documentation

## Actual Output

No group is being shown in the generated documentation page (HTML)

## Expected Output

I can see the Relations group and the relations on the documentation page (HTML)

## Environment details:

* OS: macOS Sierra
* Ruby version (`ruby -v`): 2.3.1
* YARD version (`yard -v`): 0.9.5

I have read the [Contributing Guide][contrib].

**Comment by lsegal** [comment]
Are the actual items being displayed, or is are only the group names missing? If it's the former (no items), then it's probably because YARD does not recognize `belongs_to`/`has_many` and other Rails specific declarations out of the box without any plugins. Unless you're using specific plugins or explicitly documenting with `##` or directives, these will not show up in documentation.

**Comment by bakku** [comment]
I'm sorry, I didn't know that plugins are needed for this specific behaviour. Thanks :)
