### ISSUE TITLE
Ignore defined constants

### ISSUE THREAD

**Issue by handicraftsman** [lsegal/yard#1080]
I have 100+ constants imported from [this](https://tools.ietf.org/html/rfc2812#section-5) RFC and i have provided link. How do i mark all these constants as documented without actually writing comments for each?

**Comment by lsegal** [comment]
@handicraftsman unfortunately if they're not documented, then they're going to be listed as undocumented. There's no way, nor is there any value, to faking this. Even if you tried to fake this, the stats provided by YARD are only one view into how documentation percentage is calculated. Other tools may do this in other ways, and other usages of YARD may even generate different stats (depending on visibility, filters, etc).

At the end of the day, if there's nothing written about an object, it's inherently undocumented. If your goal is try to artificially raise your documentation count, you can generate fake comments that just say `The RPL_... code` or something of the like. But really, you _should_ be documenting these constants, since they _will_ be seen by users reading your library documentation, and, presumably, users _will_ need to use them, so they will need to know what something like `RPL_YOURHOST` actually means.

Sidenote: if users are _not_ using these constants, you can mark the constants private with `private_constant` which should keep them out of your docs and therefore out of your doc stats.

**Comment by lsegal** [comment]
It's completely reasonable to reference the RFC at the top of your module, and if this is your solution, it's a completely fine one. That said, adding a reference to a specification document is not a _replacement_ for documentation of your own library. YARD's statistics exist as an _approximation_ to how good of an experience your documentation is providing. In other words, is there something more that can be done to make the library more understandable to users? If so, then it would be wrong for YARD to report 100% coverage.

In this case, it would be _just_ as inaccurate to say that linking to an RFC file at the top of your module provides a perfect (100%) documentation experience, just as it would be to say it's an unacceptable (0%) documentation experience. The real answer is likely somewhere in the middle, but the only difference between these two wildly inaccurate approximations is that one of them makes you feel better about yourself-- and if that's the goal here, then the value of these statistics is being misused.

If you care about having a good documentation experience for your users, and it seems like you do based on your interest in having 100% coverage, then linking to an external doc should really not pass the muster. Ask yourself the question that YARD is asking you: is there really nothing else you can do to make this better? I'm not necessarily a user of your library, but if I were, having the documentation inline would be an objectively better experience than having to cross reference what is effectively a text file. It does seem like there is more you can do. 

Is documenting a ton of constants that are defined somewhere else an expensive process? Sure. Does that mean you can call your work done? If you think the costs outweigh the benefits, possibly. But does that mean your work is _actually_ done? I don't think it does. YARD doesn't either, and that's what it's telling you in the stats.

I'm marking this as closed since this was a question that I believe I've answered as best I can. I realize this might not be what you are looking for, but hopefully this helps!
