### ISSUE TITLE
Grouping together high level concepts

### ISSUE THREAD

**Issue by ioquatix** [lsegal/yard#1085]
I'd like to know if it's possible to group together high level concepts, and perhaps control the order in which the are listed, on the left hand side class list. I looked at the YARD documentation but couldn't see anything which could do it.

The idea is, for new users, to quickly allow them to see the core concepts within a library.

**Comment by zverok** [comment]
(I should add here that typicall Rails project documented with YARD looks like a mess, because it is usual to not uses any namespaces there, and conceptually different things like models, controllers, decorators, services and whatnot are all mixed up in class list.)

**Comment by lsegal** [comment]
AWS SDK for Ruby does this with extensions:

http://docs.aws.amazon.com/sdkforruby/api/index.html

Code here: https://github.com/aws/aws-sdk-ruby/tree/master/doc-src

**Comment by ioquatix** [comment]
Is it possible that we can consider this should be a core part of yard?

**Comment by lsegal** [comment]
This seems more appropriate as a plugin in my opinion. If there was heavy usage of this use case, it would be easier to have a conversation about pulling an existing plugin into YARD.

**Comment by ioquatix** [comment]
Perhaps a new `@tag` directive, and then in the project, a way of listing tags by priority? Then, a modification to the code that generates the sidebar to take this into account?

**Comment by lsegal** [comment]
I'm afraid there are no short term plans to put something like this into core. It's feasible to do this using standard extensibility mechanisms and publish a plugin for this if you want to provide it to others. You can use the code provided above as a base.

I'm going to mark this as closed since a plugin is the better approach.

**Comment by ioquatix** [comment]
I don't really have the time for this unfortunately, nor to maintain a separate plugin.

**Comment by lsegal** [comment]
I would add that there is more than enough to get you started in the AWS SDK for Ruby example.

That said, if your goal is to group and explain your API, this seems like a better job for guide-style documentation / extra files. Having a conceptual "Services" or "Controllers" grouping in your listing is actually not _that_ advantageous, because there is zero context for that grouping to new users. You can also do this fairly easily by simply relying on well named namespaces (like `Foo::Services`). The only useful thing here would be moving important items to the top, but that is relatively easy to do with template customization.
