### ISSUE TITLE
[warn]: in YARD::Handlers::Ruby::AttributeHandler: Undocumentable FIELDS

### ISSUE THREAD

**Issue by pioz** [lsegal/yard#1106]
I've a class like this:

```
class A
  FIELDS = [:field1, :field2, :field3]
  attr_reader *FIELDS
end
```
when I generate the doc with `yard doc --no-private -mmarkdown` i get:
```
[warn]: in YARD::Handlers::Ruby::AttributeHandler: Undocumentable FIELDS
	in file 'lib/a.rb':3:

	3: attr_reader *FIELDS

```
What is the best way to handle this warning?
Is there a way to suppress this warning?
## Environment details:

* OS: OSX 10.12.6
* Ruby version (`ruby -v`): ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
* YARD version (`yard -v`): yard 0.9.9

**Comment by lsegal** [comment]
The recommended way is to document your attrs, which you can't do in a single liner. You should do:

```ruby
class A
  # docs for field 1
  attr_reader :field1

  # docs for field 2
  attr_reader :field2

  # docs for field 3
  attr_reader :field3
end
```

If you _really_ don't care about the docs but want them to at least show up, you would use literals instead of constants. YARD cannot evaluate runtime code, even if that code may be a constant. This could work too:

```ruby
class A
  attr_reader :field1, :field2, :field3
end
```
