### ISSUE TITLE
parse java files 

### ISSUE THREAD

**Issue by saxenadeepakkumar** [lsegal/yard#1127]
Can we use yard to parse java files to generate document. Is there any existing java parser available?

Please help. I am new for ruby.

**Comment by lsegal** [comment]
YARD does not support parsing of Java files, but you could write a plugin to do so. See http://github.com/lsegal/yard-js for an example of this. I don't know of any Java parser libraries written in Ruby, though. Fortunately, because of its strict syntax rules, parsing Java, at least for method declarations, could be fairly straightforward with simple tokenization.
