### ISSUE TITLE
[Request] Custom highlight syntax

### ISSUE THREAD

**Issue by noraj1337** [lsegal/yard#1137]
Hi,

This is a request.

It should be great if YARD could support custom syntax highlight. It's already possible to give YARD some option to use custom markdown renderer, so why not the same for syntax highlight?

The actual syntax highlight is not very sexy (from my POV) for code blocks and it is nearly impossible to make the difference between inline code and normal text.

Code block, plain/raw (we can see the difference) : 

![](https://i.imgur.com/hMGY4OO.png)

Code block, ruby highlight (not sexy but works) : 

![](https://i.imgur.com/yz1ZUtI.png)

Inline code (different size and/or font but look a lot like normal text) : 

![](https://i.imgur.com/MiCXGPb.png)

This

![](https://i.imgur.com/SPyXSI4.png)

or this

![](https://i.imgur.com/ZrUunZk.png)

is much more readable for inline code.

Even if only one syntax highlighter is supported the needed is feature is to allow the user to choose the theme.

From user POV this can be `--syntax-highlight highlightjs` and `--syntax-highlight-theme color-brewer` (native theme), or `--syntax-highlight rouge` and `--syntax-highlight-theme tulip`, or even `--syntax-highlight prismjs` and `--syntax-highlight-theme okaidia`.

+ [highlight.js](https://highlightjs.org/): ([usage](https://highlightjs.org/usage/))
+ [prism.js](http://prismjs.com/): ([usage](http://prismjs.com/#basic-usage))
+ [rouge](http://rouge.jneen.net/): ([usage](https://github.com/jneen/rouge#usage))

**Comment by lsegal** [comment]
You can implement your own syntax highlighting through [template customization](http://www.rubydoc.info/gems/yard/file/docs/Templates.md#Overriding_Stylesheets_and_Javascripts). Does this get you what you need?

**Comment by noraj1337** [comment]
@lsegal Let's assume I have a gem. I'm actually doing `yard doc` (with a `.yardopts` file) and then `yard server` to see it. As I understand what I need to do is (if I want to use highlight.js for example):
- create a custom template folder at the root of my project, ex: `yard_highlightjs_template`
- copy highlightjs css inro `yard_highlightjs_template/fulldoc/html/css/default.css`
- copy highlightjs JS into `yard_highlightjs_template/fulldoc/html/js/highlight.pack.js`
- create `yard_highlightjs_template/layout/html/setup.rb`:

```ruby
 def stylesheets
   # Load the existing stylesheets while appending the custom one
   super + %w(css/default.css)
 end

 def javascripts
   # Load the existing javascripts while appending the custom one
   super + %w(js/highlight.pack.js)
 end
```

- add those options in my `.yardopts` file
  + `--template template_name_here_but_dont_know_what_it_is`
  + `--template-path yard_highlightjs_template`
- find a way to add `<script>hljs.initHighlightingOnLoad();</script>` to the template.:
  + create `yard_highlightjs_template/class/html/highlightjs.erb` and I don't know how yet add the previous script loader
  + add this in my `yard_highlightjs_template/layout/html/setup.rb`

```ruby
def init
  super
  sections.push :highlightjs
end
```

Help wanted, tell me if I'm wrong.

I think this is a little tricky for non-dev people. Include this in yard and add a custom `--syntax-highlight` command option will be easier. But if add this in yard is something out of question, once I'll have figured how to create the custom template, I'll make a PR to add this as an example in [the doc](http://www.rubydoc.info/gems/yard/file/docs/Templates.md#Overriding_Stylesheets_and_Javascripts) because this is something that a lot of people will want to do.

**Comment by lsegal** [comment]
> Help wanted, tell me if I'm wrong.

This is mostly correct:

1. The path would be `yard_highlightjs_template/default/fulldoc/html/css/default.css`. Note the `default`. That's the template.
2. You don't need `--template`, since you're overriding the default template.

You can look at [yard-js](https://github.com/lsegal/yard-js/blob/master/templates/default/layout/html/setup.rb) for an example of how highlight.js can be used.

> I think this is a little tricky for non-dev people. 

Nothing is stopping you from packaging this up as a plugin for less technical people to use. Others have already done this, [yard-pygments](https://github.com/nex3/yard-pygments) and [yard-coderay](https://github.com/sagmor/yard-coderay) are examples, you can even just use those directly if you find that easier.

**Comment by noraj1337** [comment]
In fact I'm not a dev, it seems a little blurry to me. If I'm doing it it will be a dirty hack. I prefer not to create a template. And it's really heavy for everybody to have to create it's own template to do that.

Here is the final point : I _request_ for YARD to **natively** support a syntax highligther. If you don't want to add this feature you can close the issue.

**Comment by lsegal** [comment]
> And it's really heavy for everybody to have to create it's own template to do that.

Maybe I wasn't clear when I explained this above, but not everybody needs to modify the template. Creating a plugin allows other users to just use `--plugin yourpluginname` and that's it. No technical knowledge is needed for secondary users. There are already plugins available that do this, see the post above for information. The short answer is if you want syntax highlighting you can install those plugins and use `--plugin pygments` or `--plugin coderay`.

I'm going to close this issue because there are currently no plans to include customization of syntax highlighting into YARD core. The intention has always been to allow template customization through the templating architecture and plugins, and adjusting the visual styling of syntax highlighters (or any other part of the page) falls under that category.

**Comment by noraj1337** [comment]
@lsegal Yeah using plugin seems very easy. I'm not good enough to create a highlightjs plugin. OF course I read your previous comment, I understood the template functionality but didn't understand there was a simple plugin support. I'll try `yardoc --plugin coderay` it looks very simple and pure ruby.

Again you're right to close the issue, I didn't understand there was a plugin feature. That's all good, thank you very much.
