### ISSUE TITLE
Not showing all files

### ISSUE THREAD

**Issue by MarioRuiz** [lsegal/yard#1158]
When generating the documentation for other files, like CHANGELOG.rdoc or  LICENSE, those files are not included on the documentation later.
See the gemspec: https://github.com/MarioRuiz/timify/blob/master/timify.gemspec
When opening the documentation and clicking on files: http://www.rubydoc.info/gems/timify/ shows the README.md but not LICENSE

**Comment by lsegal** [comment]
rubydoc.info uses the `.yardopts` file to generate the list of extra files, not your gemspec. AFAIK no tools rely on your gemspec to list extra files except for rdoc itself. 

https://rubydoc.tenderapp.com/kb/getting-started-with-rubydocinfo/setting-up-a-yardopts-file

Marking this as closed since YARD works as expected here and the root issue is integration with rubydoc.info.
