### ISSUE TITLE
Server with --rebuild fails to reflect modifications correctly

### ISSUE THREAD

**Issue by svoop** [lsegal/yard#1165]
Working on a gem, I'm running `yard server -r` in the root of the gem to check the docs generated from my source from time to time.

When e.g. renaming a constant, reloading or force reloading the browser renders the corresponding page in the docs with both the old and the new constant (and it's value). To fix this, I have to `rm -rf .yardoc`.

:warning: There are more such effects, the one mentioned above is just the last one which has occurred.

## Steps to reproduce:

1. Define a constant on a class.
2. `rm -rf .yardoc`
3. `yard server -r`
4. The docs served show the constant and it's value.
5. Rename the constant.
6. The docs served show the constant and it's value twice (old and new name)
7. `rm -rf .yardoc`
8. The docs served show the constant and it's avlue once (only new name)

## Environment details:

* OS: MacOS 10.13
* Ruby version (`ruby -v`): 2.5.1
* YARD version (`yard -v`): 0.9.12

**Comment by dylanahsmith** [comment]
I've noticed the same problem with use `yardoc --use-cache`

It looks like the problem is that yard merges the information across files into code objects and caches those in the registry, such that there isn't an efficient and accurate way to update the cache when only a subset of files change.  The associations between code objects and files are there already, but I think it would be necessary to scan over all of them to detect which ones were removed.

It would help to have an index to all the code objects that were created from a file so that it could be compared to the code objects in a new version of the file.  With that it would be possible to detect removed code so that it can also be removed from the documentation.  Namespaces could be associated with multiple files, so files would be added or removed to that list and the namespace itself would only be removed if that set of files defining it becomes empty.

**Comment by lsegal** [comment]
YARD doesn't fully support removing objects from the store with `--reload`. The intent of the reloading webserver is to use it for updating documentation for existing projects, but not for large changesets on those projects.

It is possible to fix this, it just hasn't been prioritized. YARD actually has enough information already in the registry to address this, if someone wanted to create a PR.

> It would help to have an index to all the code objects that were created from a file so that it could be compared to the code objects in a new version of the file. 

Every object in the registry has a `.files` attribute which lists every file it was registered from. This should get you started analyzing the changeset. I do believe we invalidate files directly affected by a change, we just don't currently do a reverse diff to see what is _no longer_ present. I believe this would be a slower O(N) lookup against the full registry.
