### ISSUE TITLE
Raw data output

### ISSUE THREAD

**Issue by eugene-manuilov** [lsegal/yard#1206]
Hello,

can anyone help me to figure out how to generate documentation and get raw data output that I can store in my database? The [feature list](https://github.com/lsegal/yard#feature-list) states that it is possible, but I can't find how to do it... Thanks in advance!

**Comment by eugene-manuilov** [comment]
Thanks @lsegal! That helps! 

Is there a near future plan to make the data storage component to be backend agnostic? Or is there a way to read it with node.js? Hard to work with it when you are not a ruby guy :)

**Comment by lsegal** [comment]
@eugene-manuilov the data storage layer will always be stored in a Ruby marshaled format. This provides the best performance versus YAML or JSON formatting, which we benchmarked but found to be extremely slow at serialization given the requirements we have for normalized storage. This means that accessing the data storage will require Ruby. YARD is a tool written in Ruby, after all.

That said, you can have YARD generate output in various formats like JSON or YAML if you need to. This requires some Ruby code to load the Registry and dump all data as JSON/YAML, but after that, you can navigate the data with any other tool you'd like.

A quick and very naive version of this type of dump would be simply:

```sh
ruby -ryaml -ryard -e "YARD::Registry.load!; puts YARD::Registry.root.to_yaml"
```

NB: JSON requires a bit of work because YARD uses recursive data structures, which JSON isn't inherently good with.

**Comment by eugene-manuilov** [comment]
@lsegal for some reason i receive `can't modify frozen string` when i run following:

```
ruby -ryaml -ryard -ryard-js -e "YARD::Registry.load!('.yardoc'); puts YARD::Registry.root.to_yaml"
/var/lib/gems/2.5.0/gems/yard-js-0.1.3/lib/yard-js/core_ext/yard.rb:9:in `replace': can't modify frozen String (FrozenError)
	from /var/lib/gems/2.5.0/gems/yard-js-0.1.3/lib/yard-js/core_ext/yard.rb:9:in `<top (required)>'
	from /var/lib/gems/2.5.0/gems/yard-js-0.1.3/lib/yard-js/plugin.rb:1:in `require_relative'
	from /var/lib/gems/2.5.0/gems/yard-js-0.1.3/lib/yard-js/plugin.rb:1:in `<top (required)>'
	from /var/lib/gems/2.5.0/gems/yard-js-0.1.3/lib/yard-js.rb:29:in `require_relative'
	from /var/lib/gems/2.5.0/gems/yard-js-0.1.3/lib/yard-js.rb:29:in `<top (required)>'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
[error]: Invalid configuration file, using default options.
[error]: FrozenError: can't modify frozen String
[error]: Stack trace:
	/var/lib/gems/2.5.0/gems/yard-js-0.1.3/lib/yard-js/core_ext/yard.rb:9:in `replace'
	/var/lib/gems/2.5.0/gems/yard-js-0.1.3/lib/yard-js/core_ext/yard.rb:9:in `<top (required)>'
	/var/lib/gems/2.5.0/gems/yard-js-0.1.3/lib/yard-js/plugin.rb:1:in `require_relative'
	/var/lib/gems/2.5.0/gems/yard-js-0.1.3/lib/yard-js/plugin.rb:1:in `<top (required)>'
	/var/lib/gems/2.5.0/gems/yard-js-0.1.3/lib/yard-js.rb:29:in `require_relative'
	/var/lib/gems/2.5.0/gems/yard-js-0.1.3/lib/yard-js.rb:29:in `<top (required)>'
```
Looks like yard-js tries to modify a "constant" string, am i correct?

**Comment by eugene-manuilov** [comment]
Thanks @lsegal! My issues is solved!

**Comment by trivikr** [comment]
> @lsegal for some reason i receive `can't modify frozen string` when i run following

@eugene-manuilov How did you resolve this error?
It's currently open in https://github.com/lsegal/yard-js/issues/3

**Comment by eugene-manuilov** [comment]
Sorry, @trivikr. I don't remember, it was ~3 years ago :)

**Comment by trivikr** [comment]
Thanks @eugene-manuilov for your response.
As per my findings in https://github.com/lsegal/yard-js/issues/3#issuecomment-908681741, it needs to be fixed in yard-js
