### ISSUE TITLE
rubydoc.info doesn't collect new gem releases

### ISSUE THREAD

**Issue by MarioRuiz** [lsegal/yard#1214]
Since a few days ago rubydoc.info doesn't collect new releases of gems, for example:

https://www.rubydoc.info/gems/nice_hash/1.7.0

https://www.rubydoc.info/gems/nice_http/1.0.1

**Comment by kapoorlakshya** [comment]
Same here - https://www.rubydoc.info/gems/ffmpeg-screenrecorder/1.0.0.beta8

**Comment by rubyFeedback** [comment]
It seems we are hit hard as rubygems.org also does not show individual downloads right now ( https://github.com/rubygems/rubygems.org/issues/1884 ). While this may not be directly connected to the issue here, right now we are a bit on a flailing health situation in the ruby ecosystem to some point, compared to e. g. a few months ago.

**Comment by lsegal** [comment]
Please re-open this issue against https://github.com/docmeta/rubydoc.info if you're still experiencing it since that is the repo that manages rubydoc.info. Thanks!
