### ISSUE TITLE
[Question] Is there a way to detect invalid @param order

### ISSUE THREAD

**Issue by mensfeld** [lsegal/yard#1223]
Suppose I have a method:

```
def a(b, c)
end
```

and I provide following yard doc:

```ruby
@return [Integer] sum of a and b
@param b [Integer]
@param a [Integer]
``` 

is there a way to:

- detect, that the order of params docs does not match the order of arguments
- detect, that return is defined before the params

Thank you in advance!

**Comment by lsegal** [comment]
@mensfeld 

> * detect, that the order of params docs does not match the order of arguments

You can do this since tags are defined in order. You can compare `obj.tags(:param)` with `obj.parameters` to validate orders match similar to the way we warn for incorrect `@param` tags: https://github.com/lsegal/yard/blob/master/lib/yard/docstring_parser.rb#L275-L297

FWIW you shouldn't care about the order, since it doesn't truly matter to YARD and there should be some leniency to the way tags are defined. If this is a linting tool, this makes sense, but I would consider this to be a very _strict_ check.

* You cannot _easily_ detect the return tag being defined before params (there's a way to do it but it's not pretty, see below *), but this _typically_ doesn't matter since YARD will generate the HTML in the right order visually and it shouldn't matter what order tags are defined in (as per above).

So the ugly way to do this is to override the [DocstringParser#create_tag](https://github.com/lsegal/yard/blob/master/lib/yard/docstring_parser.rb#L209) method to check for the presence of a `@return` tag when `tag_name == 'param'`. Basically since tags are added additively, you can make sure you haven't added Y before X. Example:

```ruby
class MyDocstringParser < YARD::DocstringParser
  def create_tag(tag_name, tag_buf = '')
    if tag_name == 'param' && tags.find {|t| t.tag_name == 'return' }
      log.error 'Cannot add return before param tag'
    else
      super
    end
  end
end

YARD::Docstring.default_parser = MyDocstringParser
```

Hope that helps!

**Comment by mensfeld** [comment]
Hey. Thank you!

The reason I need that is that my (soon to be open source) quality assurance tools wrap around the yard input in order to keep our docs super tidy. That is to also make sure params are defined before return, all the variables are documented etc. See the example below:

![zrzut ekranu z 2019-02-26 19-37-15](https://user-images.githubusercontent.com/392754/53437511-00d5d180-39fe-11e9-9aaf-8b9cd3a3dca6.png)

I currently track things like:

- unknown parameter names
- undocumented method arguments
- unknown tags
- undocumented objects

and wanted to add the rest as well to make our docs way more tidy and clean.

This answer and code are enough for me to craft yet another reporter :) thank you!
