### ISSUE TITLE
XDG Base Directory Specification compliance

### ISSUE THREAD

**Issue by z0rc** [lsegal/yard#1230]
Yard uses `~/.yard` to store configuration, gem index, etc. It would be really nice to split this data to respectful folders defined by [XDG Base Dir Spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). Mainly config should go into `$XDG_CONFIG_HOME/yard/`, gem index and other generated data can be stored in `$XDG_CACHE_HOME/yard/`.

This would help with backups, keeping configuration separated from cache. But most importantly is that `$HOME` would be kept clear from unnecessary top level dotfiles. Check out how git, htop, systemd, mc and other CLI tools implement this spec.

**Comment by lsegal** [comment]
I would accept support for XDG base directory support as a pull request, but I am going to close this issue out since we have a policy to not keep feature requests open.

If you want to take a look at implementing this I don't see any reason why we can't support it, as long as we fallback to `Dir.home` when these variables are not present.

**Comment by soloturn** [comment]
@lsegal this seems more a bug than a feature request. the default should be the XDG default values not the $HOME/.yard, even when XDG_* environment variables are not set.
