### ISSUE TITLE
Stack overflow introduced for certain libraries

### ISSUE THREAD

**Issue by samphippen** [lsegal/yard#1242]
In commit c337737b43ea32136dd454f128c37fd84a188cb6 the call to [`ensure_loaded!`](https://github.com/lsegal/yard/commit/c337737b43ea32136dd454f128c37fd84a188cb6#diff-8047bf8756fb74fb708df48083f1ee9fR27) can cause an infinite recursion for some libraries. I identified this while trying to add YARD to https://github.com/googleads/google-ads-ruby. This bug did not exist in the immediate parent  a4ae6714813d88586aa4d6e07b2065d7f46ced55

## Steps to reproduce

```
#!/bin/bash
set -exuo pipefail

git clone https://github.com/googleads/google-ads-ruby
(
cd google-ads-ruby || exit 1
git checkout factories
./scripts/codegen.sh
cat <<EOD >> Gemfile
gem "yard", git: "https://github.com/lsegal/yard", ref: "c337737b43ea32136dd454f128c37fd84a188cb6"
EOD
bundle install
bundle exec yard
)
```

## Actual Output

https://gist.github.com/samphippen/5da1ff8928e9461ef6f0edfc59162c5c

## Expected Output

no stack overflow.

## Environment details:

* OS: Mac OS
* Ruby version (`ruby -v`): ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
* YARD version (`yard -v`): c337737b43ea32136dd454f128c37fd84a188cb6
* Relevant software dependency/versions:
  * [Any 3rd party libs required to reproduce, omit if none]

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
Sorry for taking so long on this, finally had some time to track it down.

Looks like YARD has been hiding an undocumentable code block until this change. The "regression" exposes the fact that YARD has been ignoring quite a few of your constant assignments.

The problem is that these constant assignments that are codegened are actually not documentable code, for ex:

```ruby
  FrequencyCapLevelEnum = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v2.enums.FrequencyCapLevelEnum").msgclass
  FrequencyCapLevelEnum::FrequencyCapLevel = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v2.enums.FrequencyCapLevelEnum.FrequencyCapLevel").enummodule
```

The constant `FrequencyCapLevelEnum::FrequencyCapLevel` is undocumentable because YARD can't resolve the dynamic lookup happening above. Previously YARD was not resolving these complex constant assignments, but now that it is, these constants are causing weird things to happen and thereby generating stack overflows.

I have a fix coming for this which will stop the StackOverflow exception alongside support for _attempting_ to document these constants. The side effect is that you will start to see a slew of previously hidden UndocumentableError warnings, i.e.:

```
[warn]: in YARD::Handlers::Ruby::ConstantHandler: Undocumentable invalid constant mapping
	in file 'lib/google/ads/google_ads/v1/enums/app_campaign_bidding_strategy_goal_type_pb.rb':22:

	22: AppCampaignBiddingStrategyGoalTypeEnum::AppCampaignBiddingStrategyGoalType = Google::Protobuf::DescriptorPool.generated_pool.lookup("google.ads.googleads.v1.enums.AppCampaignBiddingStrategyGoalTypeEnum.AppCampaignBiddingStrategyGoalType").enummodule
```

You will probably need to find a better way to codegen these constants so that YARD can understand exactly what you are doing, or, alternatively, write a plugin to properly doc this from the root .proto files directly.

**Comment by lsegal** [comment]
This will be fixed in the next release with the caveat note about extra warnings you will now be seeing.
