### ISSUE TITLE
Including RDoc meta methods in yardocs

### ISSUE THREAD

**Issue by castwide** [lsegal/yard#1254]
When generating yardocs for Rails, it doesn't include meta methods defined in RDoc. One example is the [AbstractController::Callbacks::ClassMethods#before_action](https://github.com/rails/rails/blob/8a20a40fef066ef52571f0c30aee92dd0fa36e15/actionpack/lib/abstract_controller/callbacks.rb#L100) method.

## Steps to reproduce

1. Clone rails/rails
2. Run `yardoc`
3. Run `yri AbstractController::Callbacks::ClassMethods#before_action`

## Actual Output

`undefined class/module SelectorObject (ArgumentError)`

## Expected Output

The documentation for the before_action method

## Environment details:

* OS: Windows 10
* Ruby version (`ruby -v`): 2.5.3
* YARD version (`yard -v`): 0.19.9

I'm not sure if this should be supported behavior in YARD, but it works as expected when I generate documentation for the Ruby core, so it should at least be possible. I also wrote a rough POC that resolves the issue by converting an RDoc store into to a YARD registry.

If this isn't supported, I can work around it by developing an external tool; but if it seems worth pursuing as a core feature, I'd be willing to submit a PR for it. One possibility is some kind of `yardoc --with-rdoc` option.

**Comment by lsegal** [comment]
This syntax is not supported by YARD. You're seeing it in Ruby-core for C code specifically, which actually uses a slightly different syntax from RDoc's directives. 

There aren't any plans to support RDoc directives in YARD core since they work fundamentally differently from YARD's tag architecture, though you can build a plugin to support this by overriding [YARD::DocstringParser](https://www.rubydoc.info/gems/yard/YARD/DocstringParser).

Hope that helps!

**Comment by castwide** [comment]
Cool, that makes sense. It sounds like a plugin is the way to go. Thanks!
