### ISSUE TITLE
Question about `@return [self]`

### ISSUE THREAD

**Issue by castwide** [lsegal/yard#1257]
Should `@return [self]` generally be expected to return an instance of the method's parent, or should it be expected to return the class from a class method? Example:

```ruby
class Foo
  # @return [self]
  def self.bar; end
end
Foo.bar # <= Should the return type resolve to Foo or Class<Foo>?
```

If it's the latter, how should we document a class method that returns an instance of itself? My first instinct was `Object<self>`.

**Comment by lsegal** [comment]
Using `self` is just a shortcut for the class name. If YARD had better support of unrolling type specifiers, it would probably unroll self to be Foo in the above example in docs, and would probably not handle the edge case of `Class<Foo>`. That said, it's a little misleading to use `@return [self]` at a class level method, since it's unclear to a reader at the source layer what the intent is-- in other words, it's not clear if you are relying on the existing the semantics of the doc tool or if you are incorrectly documenting the method.

The more straightforward path would be to simply use `@return [Foo]`.

**Comment by castwide** [comment]
Yeah, that's exactly my concern. The existing semantics behave the way I want, but it's ambiguous to the reader. The issue with `@return [Foo]` is that I want the return type to be transitive; e.g., if `Foo2` extends `Foo`, it can be inferred that `Foo2.bar` returns `Foo2`.

I take it there's no official way to express that? Should I just make up my own keyword, like `@return [this]` or something?

**Comment by lsegal** [comment]
You could use `Class<Foo>` to communicate that the return type is a subclass of Foo, which should provide sufficient inference that it is of the type of class alongside some prose to clarify in the docstring.

**Comment by castwide** [comment]
I was under the impression that `Class<Foo>` would return the class itself instead of the instance, e.g., `String#class` would return `Class<String>`.

**Comment by lsegal** [comment]
You're correct-- I misspoke and got confused by the very thing I mentioned above.

> My first instinct was `Object<self>`

This is what I was trying to concur with. I think this would be the best way to go in the absence of any Ruby keywords to help communicate intent. You can, of course, invent your own (like `instanceof<self>` or `instanceof<Foo>`) but I think without precedent in the language it won't necessarily be any better understood than the above. 

So yes, your first instinct was the correct one.

**Comment by castwide** [comment]
Perfect. Thanks for the clarification.
