### ISSUE TITLE
--list-undoc does not work for in-block defined methods

### ISSUE THREAD

**Issue by mensfeld** [lsegal/yard#1273]
When running:

```
yard stats --list-undoc --private --protected --charset utf-8 --markup markdown --no-progress --compact .
```

on a code like that:

```ruby
# Test
class Presence
  def safe_fetch_headers(input)
    input['headers'].is_a?(Hash) ? input['headers'] : EMPTY_HASH
  end

  def safe_fetch_context(input)
    return EMPTY_HASH unless input['body'].is_a?(Hash)
    return EMPTY_HASH unless input['body']['details'].is_a?(Hash)

    input['body']['context']
  end
end
```

I get the following output:

```
Files:           1
Modules:         0 (    0 undocumented)
Classes:         1 (    0 undocumented)
Constants:       0 (    0 undocumented)
Attributes:      0 (    0 undocumented)
Methods:         2 (    2 undocumented)
 33.33% documented

Undocumented Objects:
Presence#safe_fetch_context     (test.rb:7)
Presence#safe_fetch_headers     (test.rb:3)
```

but when executed for this code:

```ruby
# Test
class Presence
  schema(type: :native) do
    def safe_fetch_headers(input)
      input['headers'].is_a?(Hash) ? input['headers'] : EMPTY_HASH
    end

    def safe_fetch_context(input)
      return EMPTY_HASH unless input['body'].is_a?(Hash)
      return EMPTY_HASH unless input['body']['context'].is_a?(Hash)

      input['body']['context']
    end
  end
end
```

the result is as followed:

```
Files:           1
Modules:         0 (    0 undocumented)
Classes:         1 (    0 undocumented)
Constants:       0 (    0 undocumented)
Attributes:      0 (    0 undocumented)
Methods:         0 (    0 undocumented)
 100.00% documented
```

**Comment by lsegal** [comment]
Sorry for the late reply as this issue fell off the radar.

This is actually expected behavior in YARD as those methods are not actually processed, and as such, are never actually defined as methods. You can confirm this in your output, which shows 0 methods being detected.

This may be a little bit of a gotcha, but by default, YARD does not dive into arbitrary blocks, in this case, `schema do ... end`. For YARD to do this reliably, it would need to know the resulting context of the defined methods in the block, i.e., are they class methods, on which class are they being defined, etc. A block can change the way those methods show up pretty significantly via eval or instance_exec, and so to avoid misidentifying these blocks, YARD ignores them.

The general workaround for this type of thing is to write a YARD extension or plugin that triggers parsing of these blocks, or to use the `@!method` directive to define these methods manually. Incidentally, you can find details on both of these methods in https://github.com/lsegal/yard/issues/1295#issuecomment-565195823 where this recently also came up.

One _opportunity_ to note here is that YARD _could_ do more to warn about undocumentable methods. YARD is known to warn about undocumentable syntaxes, and arguably it would probably be helpful, or at least less confusing, if in this case YARD generated an undocumentable method warning for methods defined in sub-blocks. That seems like something we could improve on if someone wanted to pick this up as a feature addition. The only issue to watch out for when doing this would be to have a good way to _turn off_ these warnings when other extensions/plugins end up correctly parsing the method, but that could theoretically be feasible with some heuristics on the [YARD::Docstring.after_parse](https://www.rubydoc.info/gems/yard/YARD/DocstringParser#after_parse-class_method) callback.

Anyway hope that helps!

**Comment by mensfeld** [comment]
Answer sufficient enough :) thanks (again)!
