### ISSUE TITLE
RubyMine / Yard compatibility with object created from method inherited by ancestor

### ISSUE THREAD

**Issue by luke-hill** [lsegal/yard#1282]
## Steps to reproduce
1) A png file of any image
2) RubyMine editor (May or may not be required)

```
    require "chunky_png"

    # @return [Array <ChunkyPNG::Image, ChunkyPNG::Image>] an array of images
    def images
      [
        red_3_x_3_square,
        red_3_x_3_square
      ]
    end

    private

    def red_3_x_3_square
      ChunkyPNG::Image.from_file('insert_file_name_here')
    end
```

## Actual Output

RubyMine / Yard marks this as incorrect, because apparently images returns a `ChunkyPNG::Canvas`

It doesn't. It returns an Image, because thats the method (However from_file is inherited from `Canvas` and then included into that via `module.include`

## Expected Output

No issue

## Environment details:

* OS: Ubuntu Bionic patch 3
* Ruby version (`ruby -v`): ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
* YARD version (`yard -v`): yard 0.9.20
* Relevant software dependency/versions:
  * just install the latest version of chunky_png

Apologies if this isn't fully a yard issue, or a 3rd party compliance issue.

**Comment by lsegal** [comment]
Sorry about the delay on responding to this!

This seems like something that may need to be reported against RubyMine. YARD itself doesn't actually mark anything as incorrect, as those type specifications are freeform values that are left to tooling to process. YARD's HTML generation is _one_ tool that processes and creates HTML links between detected types, but presumably RubyMine is using its own tooling to process the types here.

As a sidenote, the type `Array<ChunkyPNG::Image, ChunkyPNG::Image>` is, at least according to YARD's _suggested format_, redundant.

If your intent is to return an array with sequential elements, you actually want `Array(ChunkyPNG::Image, ChunkyPNG::Image)`, note the parens instead of brackets, which indicates sequential vs generic value types. 

You can get a sense of how YARD interprets these values via https://yardoc.org/types -- but again, when I say "how YARD interprets", I mean YARD itself. Other tooling may define different formats or syntaxes to represent types. YARD's recommended type specification syntax is notably incomplete and cannot represent _all_ Ruby types (though it has support for this specific case), so other tooling may or may not decide to use the same specs.

You may try changing the formatting to the above, but if that still doesn't work, you may want to ask RubyMine how they expect this type to be specified in their tooling.

**Comment by luke-hill** [comment]
Oddly enough, this is no longer an issue with a later version of RubyMine 2018
When I was originally using 2018.1.6 this occurs, but now it doesn't. The yard comments seem fine.
