### ISSUE TITLE
method definitions within class_eval blocks are not captured

### ISSUE THREAD

**Issue by Fire-** [lsegal/yard#1295]
## Steps to reproduce

This is the minimal reproduction for the issue. I've done my best to remove
all extraneous code and unique environment state on my machine before providing
these steps:

1. Save the following as class_eval.rb
```ruby
module TestModule
  class MyClass
    #
    # prints test string
    #
    # @param [String] str string to print
    #
    # @return [void] no return
    def class_def_test!(str)
      puts str
    end
  end

  TestModule::MyClass.class_eval do
    #
    # prints test string
    #
    # @param [String] str string to print
    #
    # @return [void] no return
    # @!method class_eval_def_test!
    def class_eval_def_test!(str)
      puts str
    end
  end

  #
  # prints test string
  #
  # @param [String] str string to print
  #
  # @return [void] no return
  def module_def_test!(str)
    puts str
  end
end
```
2. Generate documentation for `class_eval.rb` ( `yard doc --no-private --debug --verbose --list class_eval.rb` )

## Actual Output

```
class_eval.rb:1: TestModule
class_eval.rb:2: TestModule::MyClass
class_eval.rb:9: TestModule::MyClass#class_def_test!
class_eval.rb:33: TestModule#module_def_test!
```

## Expected Output

```
class_eval.rb:1: TestModule
class_eval.rb:2: TestModule::MyClass
class_eval.rb:9: TestModule::MyClass#class_def_test!
class_eval.rb:22: TestModule::MyClass#class_eval_def_test!
class_eval.rb:33: TestModule#module_def_test!
```

## Environment details:

* OS: OSX 10.14.6
* Ruby version (`ruby -v`): ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]
* YARD version (`yard -v`): yard 0.9.20

## Notes

(Unsure of relevancy) While YARD does not seem to be aware of functions defined in this manner at all, [solargraph](https://github.com/castwide/solargraph) interprets definitions within the `class_eval` block as methods defined atop the root module directly, 
  e.g., `TestModule#class_eval_def_test!`

-----

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
This is a known limitation. YARD doesn't, by default, drop into any blocks, and especially not eval'd blocks, because it's impossible without _executing_ the code to know for sure what the block actually does.

There may be a heuristic in which top-level eval blocks _could_ be parsed, but the expected way to handle this is to either:

1. Write a plugin or custom loaded code to tell YARD to parse these blocks. You can do this by writing a [custom handler](https://github.com/lsegal/yard/blob/master/docs/Handlers.md). Haven't tested but something like:

```ruby
class EvalHandler < YARD::Handlers::Ruby::Base
  handles method_call(:class_eval)

  process do
    parse_block statement.block, scope: :class
  end
end
```

2. Use YARD's directives to manually define this, which is probably the easier way to do it. In this case, it looks _almost_ the same but requires a simple directive call:

```
class TestModule::MyClass
  # @!method class_eval_def_test!(str)
  #   prints test string
  #
  #   @!scope class
  #   @param [String] str string to print
  #   @return [void] no return
  TestModule::MyClass.class_eval do
    def class_eval_def_test!(str)
      puts str
    end
  end
end
```

Hope that helps!

PS: you should not use the `@!method ...` you have in your current provided docstring, since it is not specified in the correct manner. The correct manner to use a directive is as listed above.

**Comment by Fire-** [comment]
> This is a known limitation. YARD doesn't, by default, drop into any blocks, and especially not eval'd blocks, because it's impossible without _executing_ the code to know for sure what the block actually does.

This is fair, I didn't realize it didn't drop into blocks.

> There may be a heuristic in which top-level eval blocks _could_ be parsed, but the expected way to handle this is to either:
> 
> 1. Write a plugin or custom loaded code to tell YARD to parse these blocks. You can do this by writing a [custom handler](https://github.com/lsegal/yard/blob/master/docs/Handlers.md). Haven't tested but something like:
> 
> ```ruby
> class EvalHandler < YARD::Handlers::Ruby::Base
>   handles method_call(:class_eval)
> 
>   process do
>     parse_block statement.block[1], scope: :class
>   end
> end
> ```

This _might_ be the "best" (if not necessarily "correct") solution for my use case: `class_eval` on a globally loaded lib module from within other modules that are used mostly for code segmentation; In specific, the class within the module being defined upon is not in the same file as the class_eval block that is defining methods upon that class - a single file was just the simplest example to show the same behavior.

> 1. Use YARD's directives to manually define this, which is probably the easier way to do it. In this case, it looks _almost_ the same but requires a simple directive call:
> 
> ```ruby
> class TestModule::MyClass
>   # @!method class_eval_def_test!(str)
>   #   prints test string
>   #
>   #   @!scope class
>   #   @param [String] str string to print
>   #   @return [void] no return
>   TestModule::MyClass.class_eval do
>     def class_eval_def_test!(str)
>       puts str
>     end
>   end
> end
> ```
> 
> Just to be clear, option 2 is a much better method and the recommended path.

I think the only issue here ( and the primary reason I'm not simply re-opening the class to begin with ) is that I've previously run into races where modules would like to add definitions onto the class, and have opened the class before it was actually loaded/defined in its own lib; This then causes the lib's own initialization steps to fail.  
`class_eval`, in contrast, fails if the class doesn't already exist, which, within a rails ecosystem, triggers `const_missing` and results in the class being loaded at that point in time ( and then the requested definitions are added. ) 

> PS: you should not use the `@!method ...` you have in your current provided docstring, since it is not specified in the correct manner. The correct manner to use a directive is as listed above.

Yeah, that was included by mistake from when I was trying various methods of forcing definition documentation. Its existence does not appear to change the behavior of the example.

> Hope that helps!

Definitely! I still wish there was a standardized/built-in way of noting that an *_eval block should be treated as a method/class block, but I believe I can work with this; Thank you! Is there something out of this issue that I might be able to contribute upstream, or do you think this may be too much of an edge case?

**Comment by lsegal** [comment]
> I think the only issue here ( and the primary reason I'm not simply re-opening the class to begin with ) is that I've previously run into races where modules would like to add definitions onto the class, and have opened the class before it was actually loaded/defined in its own lib; This then causes the lib's own initialization steps to fail.

This is generally the wrong way to go about solving such a problem. If you want to force the const to be loaded prior to your usage, either `require` it directly (to explicitly indicate your monkey-patch dependency to both humans AND tooling) or use the full const name when opening the class to force Rails to perform the lookup for you:

```ruby
class << TestModule::MyClass
  def mymethod; end
end
```

The code you're using of `A::B.class_eval do` is basically doing exactly this same thing, but with the downside of an eval. TL;DR you can do this without eval using the above syntax. 

**THAT SAID**, you should REALLY be using modules to append behavior that rely on prior class dependencies rather than overriding behavior in the class directly. The safest way to do this would be to use a module with include:

```ruby
module MyMixins
  def class_eval_def_test!(str) end
end

TestModule::MyClass.extend(MyMixins)
```

That way MyMixins will always sit at the end of the inheritance chain which not only allows you to call super but also doesn't create any kind of overwriting race chain. This assumes you're not using any kind of metaprogrammed directives in the definition of the module-- I guess if you're doing that, the first example is the better path.

> Thank you! Is there something out of this issue that I might be able to contribute upstream, or do you think this may be too much of an edge case?

There aren't any plans to change this behavior. Given how easy it is to shoot yourself in the foot by jumping into eval blocks (95% of the time anything in eval is gonna be undocumentable) and how easy it is to workaround, YARD's approach is to be explicit about how things get documented. There is perhaps a more general "jump into this block" directive that could be added to YARD, i.e. `@!parse_block` which would force any block to be parsed as top level definitions, but it would still require explicit calling at which point you may as well use the above code example instead (although I guess you could bind a macro to a DSL method to trick YARD into automating this for you? that wouldn't be recommended or widely supported).

**Comment by lsegal** [comment]
Marking this issue as closed due to inactivity.
