### ISSUE TITLE
Specifying how to ignore code a code line.

### ISSUE THREAD

**Issue by mdayaram** [lsegal/yard#1309]
I tried looking around at the docs and couldn't find anything apart from writing a custom parser which I'd really rather not do.

Basically, in our code base, we have a helper method that annotates method declarations in a class.  It looks like this:

```ruby
# @param arg [Thing] the thing to do
# @return [Done]
annotate permission: "restricted", to:
def do_the_thing(arg)
  ...
end
```

The way it works is that the `annotate` method takes in a keyword list of options, and the last option, the `to:` keyword takes in a symbol representing the method to which to apply these options to (the style depends on `def` returning a symbol of the method that was just defined)

When generating the documentation for the above code though, it seems to try to attach the documentation to the `annotate` command rather than the `do_the_thing` method.  Even more surprisingly, the documentation renames this method's name to something that is an argument to the `annotate` method.

While running `yard doc`, I also sometimes (not in all cases) see the following output:

```
[warn]: in YARD::Handlers::Ruby::DSLHandler: Undocumentable method, missing name
	in file 'my/file/path.rb':130:

	130: annotate permission: { capability: TargetCapability::SEARCH }, to:
```

## Steps to reproduce

I created a small example displaying this issue (including the generated docs) in this repo here: https://github.com/mdayaram/yardoc-annotation-issue/blob/master/test_yard.rb

Currently hosting the generated docs here: https://www.noj.cc/yardoc-annotation-issue/doc/TestYard.html

## Actual Output

You can see how the `class_method_test` and `instance_method_test` are not anywhere in the documentation, but instead, the methods `restricted` and `low` seem to be documented on their behalf.

## Expected Output

For the methods to be documented correctly.

## Environment details:

* OS: OSX Catalina
* Ruby version (`ruby -v`): 2.5.7
* YARD version (`yard -v`): 0.9.20

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

**Comment by lsegal** [comment]
This is an interesting use case that frankly is difficult for YARD to support reliably.

The problem here is that, from YARD's perspective, there's nothing to suggest that you aren't documenting the DSL method itself. Consider what this would look like if you were using a hypothetical variant of `attr_accessor`:

```ruby
# @param arg [Thing] the thing to do
# @return [Done]
attr_accessor :do_the_thing, override_get:
def do_the_thing(arg)
  ...
end
```

YARD does have basic decorator support, but I believe right now it's effectively opt-in via hardcoded handlers because you have to tell the tool what semantic effect the decorator has on the method, where to attach the docs, etc. YARD won't just jump to your `def ...` and attach docstrings there because it is fundamentally ambiguous as to where those docs belong.

All this to say it's unlikely you will get around this without writing a custom handler. You can choose to put the annotation above the docs like:

```ruby
annotate permission: "restricted", to:
# @param arg [Thing] the thing to do
# @return [Done]
def do_the_thing(arg)
  ...
end
```

But failing that, your only option here is to tell YARD about your decorator. Fortunately, it's not that hard to do. public/protected/private [achieve this using process_decorator](https://github.com/lsegal/yard/blob/872b3acafe33e94932d4a3f4bcfa6981ee7bed1e/lib/yard/handlers/ruby/visibility_handler.rb#L3-L23), but your case is actually simpler:

```ruby
class AnnotationHandler < YARD::Handlers::Ruby::Base
  handles method_call(:annotate)
  namespace_only

  process do
    meth = statement.jump(:def, :defs)
    meth.docstring = statement.docstring
    parser.process([statement.jump(:def, :defs)])
  end
end
```

Place this in a Ruby file in your source tree and add `-e path/to/my_handler.rb` to your `.yardopts` file and everything will work out.

As for handling this in YARD, there are _some_ heuristics we can apply, but making assumptions about metaprogrammed decorators is a dangerous game.  The general expectation of the decorator syntax is that they make a change to the method itself, and so if your decorator is not actually touching the method object in metaprogramming terms, I would strongly recommend not relying on method-returns-a-symbol syntax to do what you're doing. Obviously changing code based on a doc tool is a pretty drastic measure, but IMO you have another option here which is to redo this API to be more traditional, i.e.:

```ruby
annotate permission: :restricted, to: :do_the_thing
```

There are a bunch of nice things about doing it this way, none of which involve me saying "YARD supports it":

1. You can separate concerns which helps as you scale. A few things here but (a) it's likely that once you get enough methods with enough permissions you'll want to keep track of them separately from the methods themselves, possibly even define them in a separate file. and also (b) it's possible you may love this syntax and want to keep adding more decorators-- but stuffing all that info before your method will almost certainly create a huge mess. Separating out the semantic declarations from your syntax will make it easier for you to manage all these concerns.

2. Your code linter/formatter won't freak out. Maybe you're not using a code formatter, but I guarantee your code formatter hates this syntax too. You have a keyword argument on the same indentation level as the method call-- I can't imagine any kind of automated formatter or linter tool liking this.

3. You can document the annotation itself! The very thing that got us into this mess, yes, but consider that you may actually want to say a few words about why you set this the permission:

```ruby
# @date 10/12/2019
# @reason Because the method was being abused.
annotate permission: :restricted, to: :do_the_thing
```

You may also need custom handler code in this case to define permission correctly (though macros could actually do this), but the idea here is that you can actually document your metadata, not just the method, and again, you can document this stuff separately so as to not overload information on `do_the_thing` itself depending on how your ACL stuff is working. You can use custom templating to display all your method permissions together, or build really simple custom tooling to collect all these permissions into a Markdown file that you can generate periodically for your users. You can of course do this with a standard method documentation using the same tags, but this avoids coupling semantic metadata and Ruby-level docs (i.e. you can avoid explaining why you set semantic-level restrictions on a method while also trying to explain what the method does all in one docstring). With `@!macro` syntax you can even DRY up the way you define these, but I won't get into that here.

The beautiful thing about this syntax is your API already supports it, so it's not a matter of changing your `annotate` helper, just how you use it.

For bonus points you could even support this the way public/private/protected work and use forward-looking declarations to group the annotations. Specifically, these methods hook into [method_added](https://apidock.com/ruby/Module/method_added) when no symbol is provided to make all subsequent method declarations use the visibility setting previously defined. In terms relevant to your API, this would look something like:

```ruby
def method1; end # not restricted

permission: :restricted

def method2; end # this is restricted
def method3; end # this is restricted too!
```

That makes it really DRY if you're dealing with groupings of ACL, which it seems like you might want in your case, although admittedly I don't know exactly how your decorator is being used.

Anyway there's a lot here but hope some of this helps!

**Comment by mdayaram** [comment]
This is insanely helpful! Thank you so much!  It'll take me sometime to digest it all, but once I'll do, I'll let you know how things go!  

Thanks again!
