### ISSUE TITLE
Use module having constants as type

### ISSUE THREAD

**Issue by jeyraof** [lsegal/yard#1361]
I have module and function:

```ruby
module ROLE_LEVEL
    MANAGER = 9
    CUSTOMER = 1
    GUEST = 0
    BANNED = -1
end
```

```ruby
# @param user [User]
# @param desired_level [ROLE_LEVEL::MANAGER, ROLE_LEVEL::CUSTOMER, ROLE_LEVEL::GUEST, ROLE_LEVEL::BANNED]
# @return [Boolean]
def check_level(user:, desired_level:)
    # ~~~
end
```

How to use ROLE_LEVEL as `desired_level` parameter's type?

**Comment by lsegal** [comment]
The syntax you are using looks perfectly correct to me. Can you explain a bit more about what isn't working as expected?

**Comment by jeyraof** [comment]
@lsegal Sorry! I missed my needs.

I want to use `ROLE_LEVEL` as standalone type like:

```ruby
# @param desired_level [ROLE_LEVEL]

or 

# @param desired_level [ROLE_LEVEL::*]
```

not unpacked:

```ruby
# @param desired_level [ROLE_LEVEL::MANAGER, ROLE_LEVEL::CUSTOMER, ROLE_LEVEL::GUEST, ROLE_LEVEL::BANNED]
```

What is correct way to represent that every constants in module could be type of param?

**Comment by lsegal** [comment]
> I want to use ROLE_LEVEL as standalone type like:

Realistically it's not one, so you _shouldn't_. The actual type you're using is a Fixnum here, which means technically the type is Fixnum and those constants are not actually enforced anywhere. The specification you have already is the correct way to do it, since these are actually discrete values not connected by any class besides the numeric type, but that's probably not a relationship you want to expose.

That said, YARD type specifiers are freeform text, so if you have a syntax that makes sense to you and your users, you can choose it. `ROLE_LEVEL::*` seems reasonable enough, though it won't auto-link constants.

If you really want to emulate enum types, you have a few options:

1. You can use classes and subclassing. This wouldn't change your API, but would add considerable boilerplate and complexity to your implementation; depending on how you're using these values, it may even add some minor performance overhead:

```ruby
# @abstract Use subclassed types
class RoleLevel
  def to_i; raise NotImplementedError, 'must use subclass' end

  # @return [RoleLevel]
  MANAGER = Class.new(RoleLevel) { def to_i; 9 end }.new.freeze

  # @return [RoleLevel]
  CUSTOMER = Class.new(RoleLevel) { def to_i; 1 end }.new.freeze

  # @return [RoleLevel]
  GUEST = Class.new(RoleLevel) { def to_i; 0 end }.new.freeze

  # @return [RoleLevel]
  BANNED = Class.new(RoleLevel) { def to_i; -1 end }.new.freeze
end

# use as:
p RoleLevel::MANAGER.to_i
```

Then you can use `# @param desired_level [RoleLevel]` because it's actually a type now, just remember to `.to_i` to get the value.

2. More commonly, you can use symbols to represent the enum values. This is much more conventional in Ruby, since it treats discrete enum values the way they are meant to be treated: as discrete values. This would still mean listing each symbol out, but it simplifies the statement quite a bit:

```ruby
# @param desired_level [:manager, :customer, :guest, :banned] the desired level...
def check_level; ... end
```

This of course needs some form of mapping, but that is easy to do via a helper method and a simple Hash.

**Comment by jeyraof** [comment]
Thank you a lot! 🙇‍♂️
2nd way is reasonable to use.

**Comment by lsegal** [comment]
Np. FYI I updated the 1st snippet with a bit of a more DRY implementation. Symbols are still generally more accepted than numeric const values for Ruby APIs though.
