### ISSUE TITLE
Running `bundle exec yard server` fails by lack of webrick in Ruby 3.0

### ISSUE THREAD

**Issue by okuramasafumi** [lsegal/yard#1387]
## Steps to reproduce

1. `mkdir foo`
2. `cd foo`
3. `bundle init`
4. `bundle add yard`
5. `bundle install`
6. `bundle exec yard server`

It causes `cannot load such file -- webrick (LoadError)` when webrick is not installed (by default it's not installed in Ruby 3.0)

## Actual Output

`cannot load such file -- webrick (LoadError)`

## Expected Output

It should launch a web server to host documents without any error.

## Thoughts

Maybe using `bundle exec` is a wrong way, but if so, I think it should be documented.

## Environment details:

- OS: macOS 10.15.7
- Ruby version (`ruby -v`): ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin19]
- YARD version (`yard -v`): yard 0.9.26
- Relevant software dependency/versions:

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/main/CONTRIBUTING.md

**Comment by lsegal** [comment]
This is a difficult one because YARD doesn't actually enforce any HTTP server library dependencies on the user. As such, this is likely the expected error, but the fix would likely be to present it in a better way.

This is what the `un` library does on Ruby 3, we would likely show the same error:

```
# ruby -run -e httpd
webrick is not found. You may need to `gem install webrick` to install webrick.
```

We can probably give a slightly better message here, but the expectation would still be an error. YARD is unlikely to bundle with webrick.

**Comment by lsegal** [comment]
This is a good point. Seems like until we replace those deps we will have to pull webrick in. I will do that now.

**Comment by jaydorsey** [comment]
I tested this on one of my projects, Works great!
