### ISSUE TITLE
C extension signature replaces Ruby's on RubyDoc

### ISSUE THREAD

**Issue by jjg-dressipi** [lsegal/yard#1390]
I have a Gem on RubyGems with the Yard documentation for it on RubyDoc. The Gem is a Ruby interface to a C library and I find that some of the Ruby methods seem to have the signature of the C functions that they wrap -- an example can be seen [here](https://www.rubydoc.info/gems/librtree/0.8.7/RTree%2Ecsv_read).  The signature should be 
```
 .csv_read(io, dim, split: :quadratic, node_page: 0) ⇒ RTree 
```
The C function is [here](https://gitlab.com/jjg/librtree-ruby/-/blob/master/ext/rtree/rtree.c#L221) and the Ruby wrapper [here](https://gitlab.com/jjg/librtree-ruby/-/blob/master/lib/rtree.rb#L108).

The odd thing is that this C signature leakage happens on RubyDoc (Yard 0.9.25) but not on my local build of the documentation (0.9.26).  Is this a known issue that was fixed in the 0.9.26 release?  I couldn't see anything in the changelog nor recently closed issues.

I have read the [Contributing Guide][contrib].

[contrib]: https://github.com/lsegal/yard/blob/main/CONTRIBUTING.md

**Comment by lsegal** [comment]
I've updated the YARD version on rubydoc.info but as you suggest there isn't really a set of changes that affect file ordering and because of this, that isn't really generating any difference.

The reason could be more likely related to your Ruby version? Could you fill out the following from the issue template for your local system that works correctly?

```
## Environment details:

- OS: [Enter operating system / version here]
- Ruby version (`ruby -v`): [Enter output of `ruby -v`]
- YARD version (`yard -v`): [Enter output of `yard -v`]
- Relevant software dependency/versions:
  - [Any 3rd party libs required to reproduce, omit if none]
```

File order is capable of changing across platforms, but generally that's specific to globs. The fact that you are not seeing this issue is actually _more_ surprising, given that YARD's default glob is as follows (pulled from `yard --debug`):

```
[debug]: Parsing ["{lib,app}/**/*.rb", "ext/**/*.{c,cc,cxx,cpp,rb}"] with `ruby` parser
```

In other words, YARD is going to parse `lib/rtree.rb` before `ext/rtree/rtree.c`, so the latter documentation _should_ actually overwrite.

There are actually quite a few things involved in why you're seeing what you're seeing:

1. If the documentation is meant to apply to RTreeC and not RTree, the problem isn't overwriting docs but docs being applied to the wrong class. 
2. Ordering doesn't actually matter, technically, since this is specific to docs explicitly being applied to RTree. 
3. However, because of some weird ordering on your platform, lib/rtree.rb is being parsed last and overwriting the incorrect initial doc objects.

So the question is: why is documentation from RTreeC being applied to RTRee? Fixing this should fix the issue you're seeing. 

The general convention for naming Ruby classes in .c source is to use the name `rb_c[CLASSNAME]` or `c[CLASSNAME]`. When this syntax is seen, YARD will use the `[CLASSNAME]` part of the variable name, in this case you've used [cRTree](https://codeberg.org/jjgreen/librtree-ruby/src/branch/master/ext/rtree/rtree.c#L503-L528), so even though you've named the class internally as RTreeC, YARD is applying all of these to RTRee. 

YARD cannot parse the [rb_const_get()](https://codeberg.org/jjgreen/librtree-ruby/src/branch/master/ext/rtree/rtree.c#L501) call above to resolve the underlying class you're applying docs to, unfortunately, and relies on this naming convention to get class names out of source unless you've overridden using RDoc style directives (like Document-class, etc).

You can actually see this because [RTreeC](https://www.rubydoc.info/gems/librtree/0.8.7/RTreeC) is missing method definitions. Although you're saying it's not documented in YARD, this is not entirely accurate. You will find that if you changed the variable names, RTreeC would "correctly" be parsed and have (undocumented) methods attached to it, as is expected behavior. YARD _does_ parse C source, and it _should_ be parsing the methods from RTreeC if it was working correctly.

If you were to rename the cRTree variable to cRTreeC or otherwise use [RDoc C directive syntaxes](https://docs.ruby-lang.org/en/2.1.0/RDoc/Parser/C.html), you should be able to inform YARD of the correct C class to document.

... the other potentially easier fix is, if you're really trying to have your .c level source be ignored, to just be add a `.yardopts` file that specifies a parser glob omitting `ext`:

**in .yardopts:**

```
lib - README.md CHANGELOG.md
```

With the above. YARD will not even be _trying_ to document RTreeC, or any related C sources. This is generally _not recommended_ (since YARD generally frowns on the concept of "not documented"), but if you're going to otherwise use `@api private` to hide RTreeC anyway, this is certainly a lot simpler.

Hope that helps!

**Comment by jjg-dressipi** [comment]
Thank you for this extensive answer, I'll convert to the conventions as suggested (still a bit of a n00b at Ruby/C, not previously aware of them).

The requested information on my setup:

- OS: Linux Mint, `uname -a`
```
Linux flounder 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Ruby version: `ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]`
- Yard version: `yard 0.9.26` 

I'm running under `rbenv`, and the last two of these were run under `bundle exec ruby -v` etc.

**Comment by jjg-dressipi** [comment]
I confirm that the convention-renaming fixes this issue: I rename `RTreeC` to `RTreeBase` and the variable holding it to `cRTreeBase` (since `cRTreeC` has too many Cs in it :grimacing:), push a new release of the gem and the result is the expected documentation on RubyDoc, as [here](https://www.rubydoc.info/gems/librtree/0.8.8/RTree%2Ecsv_read).

Many thanks for your patient assistance.

**Comment by lsegal** [comment]
> so that all of my C methods can have a fixed number of arguments, then the wrapper class in Ruby can handle all of the keyword-arguments. This means I can avoid doing tricky keyword handling in C.

This makes sense.

One thing you might want to consider is implementing all of the C internal methods directly into the RTree class as private methods, then, rather than polluting the toplevel namespace with extra classes that aren't meant to be used, you can call something like `impl_csv_read(*args)` from your Ruby wrapper method. Since you're already using inheritance, that vs. a superclass with super isn't really all that different, except the benefit is there's no "Inherits: RTreeC" confusing stuff that pops up-- you simply inherit Object like a normal Ruby class would.

![image](https://user-images.githubusercontent.com/686/125685519-bd4753ee-4001-48f8-a5ff-c91a985359ef.png)

Another alternative could be to use composition and create a `RTree::Impl` internal class that is pure .c (and also omitted from docs). Your RTree initialize would create an `@impl = Impl.new` object, all hidden from the user, and delegate to `@impl`. Structurally cleaner, and although the downside is it "pollutes" namespace by creating extra classes, at least the classes here are all inside the RTree namespace, and therefore not really going to conflict or show up in user introspection. Also the Impl name can change to something more appropriate (just using the [private implementation pattern](https://en.wikipedia.org/wiki/Private_class_data_pattern)  as a base concept.

> Many thanks for your patient assistance.

Glad it's working now!
