### ISSUE TITLE
`yard -h` and `yard help doc` yield same output and do not mention other subcommands

### ISSUE THREAD

**Issue by keithrbennett** [lsegal/yard#1414]
I was trying to learn more about using the `server` subcommand, so I tried `yard -h`, but there was no mention that it even exists.

On further investigation, I found that `yard help` lists the `server` subcommand, and `yard help server` gave me the information I wanted. Also, I compared the output of `yard help doc` with `yard -h` and found they were identical.

I suggest that the output of `yard -h` be modified to explain how to get information about the subcommands other than `doc`.

```
> yard -v
yard 0.8.7.4
```

**Comment by lsegal** [comment]
This is a very old issue but I'm cleaning up issues and wanted to respond:

yard is not a classical "subcommand" type CLI, or rather, it does have "subcommands", but YARD also has a default command (`yard doc`) that is aliased to `yard`. Because of this default alias, the subcommands aren't advertised when passing flags to yard (`yard -h`), only when activating an explicit subcommand that is not doc (`yard help`).

This is legacy behavior, as `yard` predates its subcommands, but it is also the most intuitive behavior: most users will want to simply type `yard` to get their docs, and thus `yard doc` is implied by `yard`. Logically, if you as a user expect that `yard` performs `yard doc`, then it would follow that `yard --some-flag` would perform `yard doc --some-flag`, and that's how we get where we are.

It's a little awkward, and we could benefit from a line in `yard -h` to maybe provide this insight, but it's intended / expected behavior, and the alternative would likely be more confusing to a separate set of users.

Going to mark this as closed since you've likely moved on by now, but hope this helps.
