### ISSUE TITLE
# frozen_string_literal: true as overview

### ISSUE THREAD

**Issue by hacktivista** [lsegal/yard#1421]
\# frozen_string_literal: true is shown as overview instead of module overview.

## Steps to reproduce

1. Define a module on a file with proper comments.
![image](https://user-images.githubusercontent.com/5282749/148598134-ba957b97-6661-4f1f-ae5b-b418a8c49253.png)

2. Define a something within that module on a different file, without adding a comment to the module.
![image](https://user-images.githubusercontent.com/5282749/148598199-ef77fd78-c3ef-4e62-b529-e9b5ec9e45f1.png)

## Actual Output

![image](https://user-images.githubusercontent.com/5282749/148598019-994a851c-7000-46fd-b48e-4ed005b9e651.png)

## Expected Output

Should display the actual comment I did to module.

You can check the source files on https://git.hacktivista.org/leanweb

## Environment details:

- OS: ArchLinux
- Ruby version (`ruby -v`):  ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-linux]
- YARD version (`yard -v`):  yard 0.9.27

**Comment by lsegal** [comment]
This is _a little_ unrelated to the issue at hand (because you're going to run into another issue below), but you're not using `frozen_string_literal` correctly. Magic comments _must_ be present on the first (or second) line, which means those files are not correctly enabling the frozen string feature:

> Top-level magic comments must start on the first line, or on the second line if the first line looks like #! shebang line.

Source: https://docs.ruby-lang.org/en/3.0/doc/syntax/comments_rdoc.html#label-Magic+Comments

In other words, your copyright must be below the magic comment:

```ruby
# frozen_string_literal: true
#
# Copyright here...

module LeanWeb; end
```

This _does_ lead to a separate issue, of course, in that your copyright will become the docstring.

The way that you typically workaround this in YARD is either by:

A) Adding **two** newlines between your non-docstring comments and the code object:

```ruby
# Copyright here...


module LeanWeb; end # note the extra newline above
```

or,

B) Document the code object rather than leaving it blank.

```ruby
# Copyright here...

# Docs here
module LeanWeb; end
```

This is more "correct" though in many cases this may not make sense for Ruby files, so YMMV here. If you tend to use compound namespace declarations (`class A::B; end` instead of `module A; class B; end end`) you may find it easier to document each toplevel object declaration:

```ruby
#! This is hard to document:

# Copyright here...

# Useless docs here since this module is likely documented in a different file
module LeanWeb
  # Actual docs for MyActualClass
  class MyActualClass
    # impl here
  end
end

#! this is the "easier" way to do it (+/- caveats)

# Copyright here...

# Actual docs for MyActualClass
class LeanWeb::MyActualClass
  # impl here
end
```

There are some obvious pros and cons with this method, mostly around const missing errors for due to different lexical rules inside your class body, so again YMMV. Using method (A) is a completely fine approach if this causes too much churn in your codebase.

All this to say that this is currently expected behavior due to the "frozen_string_literal" in your example not being correctly detected as a magic comment.

Hope that helps!

**Comment by hacktivista** [comment]
Thanks, I appreciate a lot the time you took to explain it all so thoroughly.

I'm a bit on a predicament because:

- If I do leave two empty lines rubocop complains
- If I disable rubocop with a comment, it shows the comment in yard
- If I use the compact const style my code complains

The less hackish solution seems to be using namespaced consts through the code, and is what I'll do, though I'm not completely satisfied by that.

Feel free to close the issue. Thanks again!

**Comment by lsegal** [comment]
> If I do leave two empty lines rubocop complains

Couldn't you disable this rule globally in your rubocop.yml? Double newline is a common requirement to separate comments from docstrings when using YARD, you should not be really using that rule alongside YARD docs in general.

**Comment by hacktivista** [comment]
Indeed I don't think that would affect my codebase quality, people tend to use only one empty line to separate things unless they have an strong reason not to. So, I'm closing this now. Thanks!
