### ISSUE TITLE
webrick optional

### ISSUE THREAD

**Issue by mathieujobin** [lsegal/yard#1435]
yard is the only gem left that requires webrick in my application.
and I was wondering if it was possible to make it optional ? 

Thanks

## Steps to reproduce

use yard

## Actual Output

webrick is required

## Expected Output

webrick is not, fallback to puma

## Environment details:

- OS: Linux, what else?
- Ruby version (`ruby -v`): 2.7.5
- YARD version (`yard -v`): 0.9.27
- Relevant software dependency/versions: Rails 6.1.5

**Comment by lsegal** [comment]
WEBrick _is_ the fallback. YARD needs at least one HTTP server library on your system to function properly, specifically webrick is needed for underlying mime type parsing in `yard server`. You can blame Ruby for removing this default from the library in 3.0+. See #1387 for details.

**Comment by mathieujobin** [comment]
That is a good point.
But not without a solution.

Webrick could be set as a dev dependency for tests to pass and all.

And when puma isn't available and it falls back to webrick which is also missing. Then it would simply raise an error.

**Comment by MSP-Greg** [comment]
> webrick is needed for underlying mime type parsing in yard server

I don't use YARD server that often, so I' not familiar with the code, but...

`YARD::Server::Commands::StaticFileHelpers` is including `WEBrick::HTTPUtils`, maybe for its `DefaultMimeTypes` hash constant and `mime_type` method.  That functionality is also in `Rack::Mime`.

Since `WEBrick` isn't in the std-lib anymore, maybe switch to the Rack version?  Could be done at runtime?  Not.Sure.
