### ISSUE TITLE
Documentation of the anonymous block forwarding

### ISSUE THREAD

**Issue by konalegi** [lsegal/yard#1497]
It's more like a question, is there a way to document anonymous block forwarding introduced in ruby 3.1?
```ruby
def meth(&)
    ...
    another_meth(&)
    ...
end
```
I've tried `# @param & [Proc] txt`, but it didn't help. 
Sorry if I've missed that from documentation.

**Comment by lsegal** [comment]
I believe that this is currently unsupported behavior, but if someone wants to throw together a pull request, it can be.

**Comment by jcouball** [comment]
I have been having the same problem.

**Comment by lsegal** [comment]
Just FYI:

Generally speaking this is no different of a situation than arg forwarding via `*args`. Since YARD's static analyzer cannot determine which method you are forwarding to (and what parameters are being forwarded), in this case you would use an `@overload` tag to manage the dynamic parameters of your method call and define them explicitly. Something like:

```ruby
# @overload some_method(name = "Alice")
#   @param name [String] the name to use
def some_method(&) forward_to(&) end
```

You can throw in a `@!macro` to DRY up the docs and rely on a bit of reuability

```ruby
# @!macro orig_meth_fwd
#   @overload $0(a, b, c)
#     @param a [String] the first param
#     @param b [String] the second param
#     @param c [String] the third param

# @!macro orig_meth_fwd
def another_meth(&) orig_meth(&) end

# @!macro orig_meth_fwd
def another_other_meth(&) orig_meth(&) end

# The original method
# @!macro orig_meth_fwd
def orig_meth(a, b, c) end
```

The above full example would generate the docs below: 

![image](https://github.com/lsegal/yard/assets/686/40abee46-7444-44bc-bf7c-a00f0f8d3772)


I'm going to close this issue as not directly covered by YARD core. Since YARD correctly parses the method (just like it would with `*args` overloading and other use cases), this seems to be behaving as expected.

**Comment by jcouball** [comment]
Thanks @lsegal  I'll give that a try.
