### ISSUE TITLE
Render the option key before the option types

### ISSUE THREAD

**Issue by justinfrench** [lsegal/yard#240]
Given the following documentation of an options hash:

```
@option args [String] :some_key Something clever here
```

The following text would be rendered:

```
* (String) :some_key — Something clever here
```

This is relatively easy to scan of the documentation on a specific key given a short number of classes expected like this, but once a few classes are added, the key gets lost, like this (real world) example in a branch of Formtastic:

```
* (Array, Hash, OrderedHash, String) :collection — Override collection of objects in the association (:select, :radio & :check_boxes inputs only)
```

To aid those who are scanning the documentation for something specific, the key should be rendered first, followed by the types and then the textual description.

Thanks for an awesome tool!

**Comment by jmthomas** [comment]
@lsegal I stumbled across this old post while looking for something and I'm surprised to hear you say you think its easier for users to use
```@param [String] foo the string object```
vs
```@param foo [String] the string object```
I find the latter much clearer and have used it through the [COSMOS](https://github.com/BallAerospace/COSMOS) project. The first syntax always felt weird to me with the parameter name immediately followed by the description because without delimiters I immediately just start reading it as a sentence. While that works in this example most get weird.

Anyway thanks for the flexibility to make YARD work well for everyone's tastes!
