### ISSUE TITLE
Ruby 2.1.0, gems 2.0.0 - yard server does not see newly installed gem versions

### ISSUE THREAD

**Issue by j0rge** [lsegal/yard#721]
With Ruby `2.1.0p0` and Rubygems `2.2.0`, the yard server `0.8.7.3` does not see gem versions installed after the server start.

I run the yard server with `yard server -g -p 8000`. 

Action: install new vesion of a Ruby Gem on the instance the yard server is running from.

Expected: upon page refresh, or, at minimum, after running `yard gems --rebuild`, the Yard server should show the new version(s) of the gem(s).

Actual: the new versions appear only after the yard server restart. 

Which is a **huge** inconvenience: we can't leave the Yard server running while developers submit their new gems to the Ruby instance, somehow we need to arrange server restart each time a new version of a gem is installed.

**Comment by lsegal** [comment]
Marking this as closed since RubyGems hardcoded serving of rdoc only inside of `gem server`. This seems bad, but there is basically nothing we can do about this except to monkeypatch into RubyGems' entire gem server command, which is an equally bad idea. You should raise an issue with RubyGems to support docs agnostically.
