### ISSUE TITLE
Mardown links

### ISSUE THREAD

**Issue by fgarcia** [lsegal/yard#724]
My README.md has a section linking to internal files like this:

     ## Resources
    - [Class diagram - full](diagram_full.pdf)
    - [Class diagram - simplified](diagram_simple.pdf)
    - [Test coverage](coverage/index.html)

Now the funny thing is that although everything works just fine when I call **yard** from the command line, the generate links are different if the command was built from a **Rakefile**

From the command line, the links are like this:

    <a href="diagram_full.pdf" target="_parent">Class diagram - full</a>

From the Rakefile (notice it is adding 'http://')

    <a href="http://diagram_full.pdf" target="_parent">Class diagram - full</a>

I tested that is the output generating the docs with the task helper:

    YARD::Rake::YardocTask.new

and with a shell command:

    task 'yard' do
        sh 'yard'
    end

My .yardopts has nothing special to it:

    --no-private
    lib/**/*.rb -

**Comment by lsegal** [comment]
Closing out old issues. 

I realize this is very old, but my guess is that this is due to an environment issue, not specific to YARD. YARD itself can't tell the difference between the Rake task and running the binary directly, those differences would be related to the environment that you're running YARD in. Not sure if you're even having this problem anymore, so I will be closing this. If you really are still struggling with this, do feel free to re-open.
