### ISSUE TITLE
Yard does not see methods defined on Struct

### ISSUE THREAD

**Issue by ms-ati** [lsegal/yard#766]
When I add a method to a Struct:

``` ruby
A = Struct.new(:a) do
  def my_method
    a + 1
  end
end
```

The generated documentation does not show `A#my_method`.

**Comment by myronmarston** [comment]
The `class A < Struct.new(:a)` version is generally inferior to `A = Struct.new(:a) { }` because it includes an extra class in the ancestor chain, which is undesirable.  The other work around is this:

``` ruby
A = Struct.new(:a)
class A
  # method defs here
end
```

But that's kinda ugly.  Given that `Struct` is a ruby built in and is designed to be used with the block form ---in fact, [Ruby's docs](http://ruby-doc.org/core-2.2.0/Struct.html#method-c-new) state it is the recommended way to customize a struct--I think that yard silently ignoring the method definitions is pretty problematic.  We've shipped multiple RSpec versions with docs missing due to the fact that our struct custom method defs were ignored by YARD and we weren't aware of it.
