### ISSUE TITLE
Case sensitive tags

### ISSUE THREAD

**Issue by trans** [lsegal/yard#791]
Currently tags are case sensitive, e.g. YARD will not recognize @RETURN as @return. The question is, should it?

On one hand there is the argument that YARD s convention is for lowercase tag labels and that should be enforced to provide clarity between developers. On the other hand capitalized tag names might be preferable to some developers to allow the tags to standout.

Alternatively, the distinction in case could be utilized to separate tags that are included in the resulting documentation from those that would not. This would give developers a simple way to create developer notes, or to "comment out" a tag temporarily. 

Personally, I am not sure I like the last idea, seems like `@#tag` might  be a better means of commenting. But capitalized TODO and FIXME are the norm for developer notes, so that s a point in its favor.

**Comment by lsegal** [comment]
I currently don't see any good reason to change this, since it would be a breaking change to do so. I agree that people should treat them as case sensitive tags, but at the same time, I don't see a serious need for case sensitive tags as a hard rule, either. It would be really confusing to have both `TODO` and `todo` tags.

I am marking this as closed, and in this case, I would probably not accept a PR unless a better argument was made than `TODO` / `FIXME` (which can still be used).
