### ISSUE TITLE
Fails to resolve a class

### ISSUE THREAD

**Issue by kostia** [lsegal/yard#814]
Hello,

I have troubles generating Yard docs with following setup: http://git.io/rR0WNA.
Getting the warning:
```
[warn]: In file `lib/widget.rb':2: Cannot resolve link to BasicObj from text:
[warn]: ...{BasicObj}...
```

If in the above setup I change in `lib/scrivito/basic_widget.rb` the string `{BasicObj}` to `{Scrivito::BasicObj}`, then the error disappears.
If I remove from `lib/scrivito/basic_widget.rb` the `attr_reader` or the method `spam`, then the error disappears.
If I remove from `.yardopts` the string `--embed-mixin Scrivito::Spam`, then the error disappears.

Thanks a lot for any help!

Kostia

**Comment by kostia** [comment]
Anyone here?

**Comment by kostia** [comment]
Please help, still having this issue.

**Comment by lsegal** [comment]
Sorry about the lack of reply!

This is a known issue. Feel free to jump in with a patch via a pull request, which will speed up getting a fix in. Given the simple workaround here (using `{Scrivito::BasicObj}`), I would suggest using that instead.

The warning is coming from generating HTML for `Widget`, which is embedding the superclass methods from `Scrivito::BasicWidget` into the page. Basically, YARD is looking at Widget, which is sitting in another namespace, and trying to resolve docstrings that reference the relative class `BasicObj`, which does not exist in Widget's namespace (the root namespace). The "embed mixins" feature literally copies docstring text and renders it as if it were sitting in the embedded class. When you have relative references across namespaces, these will break when using embeds-- which is a known limitation / issue. The fix here would be to track the embedded object's original namespace and resolve references from there, which given the current rendering architecture may be a little more difficult to do (but not impossible).

That said, the bug here is that `--embed-mixin Scrivito::Spam` is embedding methods from `Scrivito::BasicWidget`. I'm not sure how that is getting triggered, but fixing this misfire on embedding should resolve your specific issue. That said, if you reference `{BasicObj}` from docs in your `Spam` module, you will run into the same problem due to the same limitation explained above.

**Comment by kostia** [comment]
Thanks for the clarification!

We could workaround the issue by using the full qualified names all over the documentation, e.g. `Scrivito::Spam` instead of simply `Spam`, which is good enough for us for now. Will see if I can come up with a fix. Thanks anyway!
