### ISSUE TITLE
{include:...} is wrapping the included text in a paragraph

### ISSUE THREAD

**Issue by nPn-** [lsegal/yard#818]
If I do exactly what is in the guide:

 # This class is cool
 # @abstract
 class Foo; end

 # This is another class. {include:Foo} too!
 class Bar; end

the output is 
"This is another class.
 This class is cool
 too!"

rather than the expected 
"This is another class. This class is cool too!"

**Comment by lsegal** [comment]
This is old, but:

The `{include:...}` syntax currently embeds full docstrings, which implies paragraphs. Embedding does not work inline in HTML. This is due to the order which YARD processes markup, meaning it would not be easy to know if the include directive was its own paragraph or not. It is possible, so I might look into it, but for now this is intended behavior. The guide documentation is misleading here and should probably be changed to reflect actual expected usage.

I'll leave this open to see if I can fix it.

**Comment by lsegal** [comment]
The above fix makes HTML generation of include calls much cleaner and has a side-effect of supporting inlined include calls. The use case in the guide should now be officially supported.
