### ISSUE TITLE
Yard 0.8.7.6 presence breaks RubyGems tests

### ISSUE THREAD

**Issue by steakknife** [lsegal/yard#831]
https://github.com/rubygems/rubygems/issues/914

An API change was suggested as a possible culprit, perhaps `has_rdoc=`

Uninstalling / reinstalling yard would be a PITA non-solution.

**Comment by lsegal** [comment]
I'm inclined to mark this as won't fix since there's actually not much YARD can do about fixing failing tests in another project's codebase. The break is likely due to `has_rdoc`, but this is something we still support and can't drop without a major version bump / breaking users.

It seems as though if a project's tests are failing due to the presence of a certain gem, or any environmental difference, it's that project's responsibility to fix that by ensuring its test suite is sufficiently isolated from those differences. We've certainly had to make changes to our YARD suite when environmental differences in various OS's, as well as a few Ruby implementations (like JRuby, Rubinius, etc.), caused failures. It seems reasonable that other projects would make the same effort-- especially since in RubyGems' case, any plugin, supported or not, could cause test failures in their suite, if they're not doing any gem isolation.

**Comment by steakknife** [comment]
Consider yourselves informed.  :)  I'll let you guys argue over who's to blame or coordinate a fix.  ;)  Until then, users can do extra work and wonder why it doesn't Just Work TM.  Might not be worth fixing, but it might be more awesome to do so.

**Comment by tenderlove** [comment]
I fixed it in rubygems/rubygems@6669d10da1c96e5ecad5e7b1ae5b5c7f62e98752.  RubyGems should isolate itself from the rest of the system during tests, so I don't think this is a YARD issue.

**Comment by lsegal** [comment]
Thank you @tenderlove! :100:

**Comment by tenderlove** [comment]
No problem! :smile:

**Comment by steakknife** [comment]
@tenderlove `== 'the man'.upcase` :beers:

—
