### ISSUE TITLE
Extra full-stop in class method summary

### ISSUE THREAD

**Issue by chrisseaton** [lsegal/yard#839]
I have a method documented like this:

````ruby
# Is this VM built on the SubstrateVM?
````

https://github.com/jruby/jruby/blob/9725d6f796122416f15287829b3cb731f3180480/truffle/src/main/ruby/core/truffle/truffle.rb#L26

It's rendered in the class method summary like this:

> Is this VM built on the SubstrateVM?.

http://lafo.ssw.uni-linz.ac.at/graalvm/jruby/doc/Truffle.html

Note the extra full-stop after the question mark. Should that be there?

yard-0.8.7.6, JRuby 9k dev

**Comment by lsegal** [comment]
Should it be there? I guess that depends on your interpretation. The issue here is that "?" is a valid suffix in the Ruby grammar, and as such, the text "SubstrateVM?" can also be interpreted as a method, `Foo.SubstrateVM?`. In that interpretation, there should be a period after the method name. YARD can't interpret the semantics of English (yet), so for now we have to treat "?" as a valid character that can represent a Ruby identifier, or we break the rules for the opposite use case (where your summary actually ends on a questionmark-method).

One general suggestion to avoid this scenario is to not ask questions in your class/method summaries. From a quality perspective, questions don't make good documentation. Tell instead of asking: 

"Returns whether the VM is built on the SubstrateVM."

YARD gives you the "Returns" prefix for free when you document with `@return` tags:

```ruby
class Foo
  # @return [Boolean] whether the VM is built on the +SubstrateVM+.
  def substrate? ... end

  # @return [String] the version of Truffle/Graal being used.
  def version; ... end
end
```

**Comment by chrisseaton** [comment]
Ok I'll change my questions to statements.

I'm not sure why Yardoc adds full stops at all though. Why not leave that up to the author?

**Comment by lsegal** [comment]
@chrisseaton from a technical perspective: since summary lines are occasionally pulled from tags (like in the `@return` case), YARD has to do some punctuation / capitalization normalization on the summary line. 

From a more opinionated perspective, one of YARD's goals it to provide high quality documentation, so the tool has a few conventions around formatting and presentation of data. One of those conventions is that every object should have a summary line written in full sentences, so the normalization of that sentence is to ensure that presentation is consistent in generated docs.
