### ISSUE TITLE
yardoc claims --list-undoc is unknown option

### ISSUE THREAD

**Issue by postmodern** [lsegal/yard#844]
yardoc 0.8.7.6 claims `--list-undoc` is an unknown option, but honors it anyways:

<pre>
$ yardoc --list-undoc
[warn]: Unrecognized/invalid option: --list-undoc
Files:          28
Modules:         2 (    2 undocumented)
Classes:        27 (   26 undocumented)
Constants:       3 (    0 undocumented)
Methods:       159 (   83 undocumented)
 41.88% documented

Undocumented Objects:

(in file: lib/sslyze/cert_info.rb)
SSLyze::CertInfo#validation
SSLyze::CertInfo#ocsp_stapling
SSLyze::CertInfo#chain
SSLyze::CertInfo
...
</pre>

**Comment by lsegal** [comment]
This is weird but expected behavior. Since unrecognized options are warnings, not hard stops, YARD keeps running, and eventually YARD passes all args through to `yard stat` under the covers to print the stats at the end. `yard stat` knows what `--list-undoc` is, and processes it normally.

**Comment by postmodern** [comment]
Sounds like `yard` shouldn't parse the options, but simply pass arguments to `yard stat` for parsing.

**Comment by lsegal** [comment]
Not *everything* is done in `yard stat`, only post processing of object statistics. `yardoc` (which is actually `yard doc`) does actual work (most of it, in fact), which requires actual arg parsing, and then calls `yard stat` unless the `yard doc` option `--no-stats` is passed:

* `yard doc --no-stats` option: https://github.com/lsegal/yard/blob/master/lib/yard/cli/yardoc.rb#L699-L701
* `yard stats` sub-command: https://github.com/lsegal/yard/blob/master/lib/yard/cli/yardoc.rb#L259-L264

The issue is that YARD::CLI::Stats needs the same options that were passed to YARD for any shared options. The only solution would be to strip out unrecognized args from YARD prior to passing off to sub-commands, but I'm not sure what the benefit of that is, since `--list-undoc` should not be passed to `yard doc` in the first place.

**Comment by lsegal** [comment]
Cleaning out old issues.

I'm marking this as WontFix since, though it is a weird UX, it is an edge case that also doesn't really *break* anything (it works when it says it doesn't, that's not quite as bad as not working when it says it does). 

Although I have no plans to take this on myself, I would accept a PR fix it assuming it didn't add significant complexity to the codebase.
