### ISSUE TITLE
`private :new` method listed as undocumented.

### ISSUE THREAD

**Issue by fappelman** [lsegal/yard#847]
If I create my documentation I get a warning that a given method is undocumented and there seems
to be no way to actually document it.

I have created a small dummy class that show the problem:

```ruby
# Dummy comment
class Example

  # Create new instance of Example
  def initialize
  end

  class << self
     private :new

     # Return global instance
     def instance
       @@instance ||= new
     end
  end
end
```

The output I get from the command `yard --protected --list-undoc --private` is:

```text
[warn]: Unrecognized/invalid option: --list-undoc
Files:           2
Modules:         0 (    0 undocumented)
Classes:         1 (    0 undocumented)
Constants:       0 (    0 undocumented)
Methods:         3 (    1 undocumented)
 75.00% documented

Undocumented Objects:
Example.new
```

For clarity my question is not about the warning (which I also don't understand) but on how to get rid of the undocumented Object. The message is caused by the line that states `private :new`. If I add a comment to the line it does not resolve the issue.

Is this a bug or am I missing something?

Regards,

   Fred

**Comment by lsegal** [comment]
It looks like `private :foo` is creating an instance of the method object in the YARD registry, thereby making it "exist" in YARD. This should probably not happen. I would accept a pull request to fix this.

That said, there are ways to document this, and there are workarounds to avoid the problem. The easiest is just to use Ruby's [Singleton module](http://ruby-doc.org/stdlib-1.9.3/libdoc/singleton/rdoc/Singleton.html)-- Ruby already provides the above functionality out of the box:

```ruby
require 'singleton'

class Foo
  include Singleton
end
```

The next workaround, albeit more awkward, would be to `undef :new` instead of marking it private and use a combination of `allocate` and `initialize` instead. Given that your initializer does nothing, you just need `allocate`. Yes, it's more awkward, but it would work until the above PR was submitted. Of course, you should just use the Singleton module here.

As for the question, `--list-undoc` is not part of the yardoc command. See #844 for more, or `yard doc --help` for valid options. You want `yard stat` if you're just looking to list your coverage.

**Comment by fappelman** [comment]
Thanks for getting back to me. The `--list-undoc` is fully clear. 

I simplified the example to make the point. Using `Singleton` implies certain limitations, i.e. I cannot pass arguments to the initialize(). So I prefer to keep it as is. I agree that using allocate and initialze() would be possible but I would prefer if this would be fixed. 

Can you elaborate what "accepting a pull request" means? I am not familiar enough with Github I guess.

**Comment by lsegal** [comment]
@fappelman,

> I simplified the example to make the point. Using Singleton implies certain limitations, i.e. I cannot pass arguments to the initialize(). 

You should never need to pass arguments to `#initialize` if it's a singleton. The only user ever calling `#initialize` on the class should be that class itself, at which point you don't actually need to call it (nor should you ever be calling `new`).I don't see why this limitation should affect your case.

> Can you elaborate what "accepting a pull request" means? I am not familiar enough with Github I guess.

Basically, I would accept a patch that fixed the behavior described in my original comment. See [GitHub docs for submitting pull requests](https://help.github.com/articles/using-pull-requests/). I don't have any plans (or time) to address this myself without a patch, since at the end of the day this is an aesthetic issue with coverage statistics of a fairly uncommon scenario (namely counting private methods in your documentation), and this specific case has plenty of easy workarounds (many of which I didn't even get a chance to mention). 

If you end up taking a stab at a fix I'd be happy to review it!

**Comment by fappelman** [comment]
@lsegal 

Figuring  out how your code works is challenging and I'm not sure that I fully grasped how to fix this properly. This simple fix does the job

It does not break any of existing `rspec` testcases.

```diff
diff --git a/lib/yard/handlers/ruby/visibility_handler.rb b/lib/yard/handlers/ruby/visibility_handler.rb
index d6c3e4c..46b0db0 100644
--- a/lib/yard/handlers/ruby/visibility_handler.rb
+++ b/lib/yard/handlers/ruby/visibility_handler.rb
@@ -17,7 +17,7 @@ class YARD::Handlers::Ruby::VisibilityHandler < YARD::Handlers::Ruby::Base
         when :string_content; source = node.source
         else next
         end
-        MethodObject.new(namespace, source, scope) {|o| o.visibility = ident.first }
+        MethodObject.new(namespace, source, scope) {|o| o.visibility = ident.first } unless source == "new"
       end
     end
   end
```

`new` is a bit of special case so maybe this simple fix is sufficient. Please let me know if this is sufficient or that I should do something different.

**Comment by lsegal** [comment]
That seems like a hack to me. As mentioned above, basically YARD should not be creating the object if it does not exist. Use `ensure_loaded!` to parse the rest of the source for this method. If it hasn't been loaded, the `MethodObject.new` operation should be skipped.

**Comment by fappelman** [comment]
I was already afraid it wasn't properly. I will look into this. Thanks for the hint where to look.
