### ISSUE TITLE
The return value for `initialize` is documented incorrectly

### ISSUE THREAD

**Issue by egonSchiele** [lsegal/yard#853]
Suppose I have this very basic class:

```ruby
class Test
  def initialize
  end
end
```

If I generate yardocs for this, the return value of `initialize` is `Test`:

    - (Test) initialize

But that is incorrect. The return value of `new` is `Test`. The return value of `initialize` is the value of the last statement. In this case: `nil`.

I hope this doesn't sound like nit-picking: this inconsistency is an issue for `yard-contracts`. See this issue: https://github.com/sfcgeorge/yard-contracts/issues/9

**Comment by lsegal** [comment]
I gotta agree with @sfcgeorge on this one. `yard-contracts` should probably handle this specific case as special, and it's probably not the last thing it would have to treat specially.

While you're technically correct, the reality is that, from a documentation perspective, it would make just as little sense to mark `#initialize` as returning nil. YARD focuses on modeling the semantic behavior of an API from the user's perspective-- we aren't trying to accurately model Ruby's runtime. This is because Ruby's runtime doesn't always reflect the actual behavior that a user expects when they use an API. From a semantic/functional perspective, your "constructor" is the initialize method, not "new".

Realistically, there would be an inconsistency no matter what we did. I've thought about this before, and none of the alternatives are any better:

* initialize returns nil: this would be counter-intuitive for users reading documentation and seeing a nil return on the constructor.
* YARD documents initialize as "new": this would be confusing to users documenting initialize and not seeing that method in documentation.
* YARD requires users to document "new" as a separate method: this would be extremely awkward because nobody does this in real world code.

Returning the class type in initialize is the least confusing of the above options. We're probably going to stick with this going forward.

**Comment by egonSchiele** [comment]
Just to be clear, I think @sfcgeorge was saying that he won't specialize `yard-contracts`. I see your point though, it could get confusing reading the documentation. Maybe the best way to handle this is to either:

1. return self in initialize
2. explicitly set the return type using `@return`.

I'm fine with this. cc @fappelman

On a side note: thank you for yardoc! Great software.

**Comment by sfcgeorge** [comment]
I don't mind the current behaviour, and I like the added "constructor" next to it to hint that there's some magic going on in Ruby but not going any further than that. It's little touches like that which make me really respect YARD, thanks! I'm quite happy for it to be left as is, and when using Contracts simply return self in initialize and contract the return type as the class name. That said, some thoughts:

Calling it new would also break cases where new has been overridden so I agree it would be confusing.

I don't think initialize returning nothing would be confusing though, it may even make more sense. All Ruby devs need prior knowledge that you call `new` but somehow `initialize` is called and you get an instance back. It's clear that `new` returns the object because that's what you called. I think it's also clear that `initialize` doesn't return anything meaningful because you could put an explicit `return 'junk'` in initialize yet `new` would still return the class instance. This will be familiar to any Java developer as constructors have no return value either. They aren't even void, they return nothing! It is the new keyword that returns the object, constructor just fills in fields. Ruby is exactly the same as this, new calls allocate to put an object in memory, then calls initialize to fill in the object, then returns it. So I agree that saying initialize returns nil would be confusing because it doesn't, it returns nothing at all. You could just not document a return value. We know it's a constructor (because we have to have learned that and YARD says so) and it's clear which class it's inside. And why do you need to know the return value of initialize—it's (nearly) impossible to call it:

```ruby
irb(main):001:0> class Foo; def initialize; end; end
=> :initialize
irb(main):002:0> Foo.new.initialize
NoMethodError: private method `initialize' called for #<Foo:0x007fc05205cd90>
```

You can with `send` but if you know enough to do that you won't be put off by documentation oddities.

**Comment by fappelman** [comment]
Would it be a possibility to add a new Pseudo type contracts named `Constructor`. Yard-contracts would be able to use that to generate insert the class name and contracts could just see this as an alias for `Any`. Just a thought.

**Comment by sfcgeorge** [comment]
A `Constructor` contract is a possibility, sitting somewhere in between the class name and void/nothing options. yard-contracts would just skip documenting it's type thus letting YARD fill it in with whatever it's default is (currently the class name).

**Comment by fappelman** [comment]
I would prefer that over being forced to put self in each constructor. Although a small effort it just feels wrong.

**Comment by lsegal** [comment]
> It's clear that new returns the object because that's what you called. I think it's also clear that initialize doesn't return anything meaningful because you could put an explicit return 'junk' in initialize yet new would still return the class instance.

I think this is all besides the point. The point here is that YARD has to (*) document a single "constructor" method, but a constructor in Ruby is actually made up of an allocator and initializer wrapped in a `.new`. Because we are effectively communicating multiple behaviors within a single "constructor" method, certain things have to be handwaved. 

What you say makes sense if you read the documentation as if it were a strict initializer method, but that's not how YARD documents it. YARD calls this a "constructor"-- a constructor must return the type of its class. This is not technically correct for initialization, but it is necessary to communicate the object construction process in its entirety to the reader of an API, because the user on the outside of the black box doesn't care how the object is initialized. 

Basically, users looking to figure out how to create a new Thing will be visiting the docs associated with `Thing`s constructor, and that would be `Thing#initialize`, because that's the Ruby convention on documenting constructor-specific behaviors. With this in mind, it *would* be weird, IMO, if the constructor documentation that the user navigated to told said user that object construction returns nil.

(*) YARD doesn't "have to" document a single constructor, but it is is a *very* strong convention in Ruby-land to associate constructor docs with the initializer. This is unlike, say, Obj-C, where there is a strong convention around explicitly creating an allocator method separate from the initializer, and since this behavior not abstracted away in the language, it can be documented cleanly as two separate things. Unfortunately to get away with this in Ruby you'd have to explicitly document `self.new`. 

(* contd.) In RDoc's world, it's typical to rewrite the signature to `self.new -> Type`, which is equally informative but slightly more misleading. YARD tries to meet users and authors half-way by being truthful about the method name (`#initialize`) while also pointing out the "special" behavior of this method in the object construction process (as, effectively, the "constructor" method when authoring such a class). The lie that YARD tells at least allows users to still understand how the constructor is implemented as well as where that implementation lives in source.

**Comment by lsegal** [comment]
Closing out old issues. The behavior here is working as intended. It *can* be confusing, but YARD is as consistent as it can be given the duality of the way object construction works vs. the convention in documenting "constructors".

**Comment by franklinyu** [comment]
> In RDoc's world, it's typical to rewrite the `#initialize` signature to `self.new -> Type`, which is equally informative but slightly more misleading.

How is it misleading here? Essentially `Thing::new` is nothing different from any other class methods except for being the only method in built-in `Object` able to allocate an instance. I can just create a `Thing::my_new` that calls a private `Thing#my_initialize` and returns a `Thing`. `::new` being special is more of a convention than a syntax thing to me.
