### ISSUE TITLE
Unexpected behavior with @!parse and @macro attach

### ISSUE THREAD

**Issue by jlindsey** [lsegal/yard#858]
I have some code that uses the idiom of mixing in a module with a `ClassMethods` submodule being automatically `extend`ed via the `included` hook. To reflect this in the documentation I have something like so:

```ruby
class Test
  include Mixin
  # @!parse extend Mixin::ClassMethods

  attribute :foo, String
end
```

In the `ClassMethods` mixin, I'm defining a DSL method and documenting it via the `@macro [attach]` tag:

```ruby
module Mixin
  module ClassMethods
    # Makes an attribute
    # @macro [attach] attribute
    #   @!attribute
    #   @return [$2] the $1 attribute
    def attribute(attr_name, type)
    end
  end
end
```

This macro is not being correctly run it seems, as the generated documentation for the `Test` class does not have an instance attribute called `foo` (or do anything at all with the `attribute` call). However, if I explicitly `extend Mixin::ClassMethods` instead of using `@!parse`, the generated docs do properly document the `attachment` DSL.

For convenience, I've created a simple test project demonstrating this: https://github.com/jlindsey/yard_test

**Comment by lsegal** [comment]
Closing out old issues, but my apologies for not ever officially responding to this.

The problem with the parse directive is that it is being associated directly on the attribute call, which means due to ordering, it is being parsed *after* the `attribute` line has been.

In order to run a directive that is not associated with any other line of code, you should separate the comment with multiple newlines. This works:

```ruby
class Test
  include Mixin
  # @!parse extend Mixin::ClassMethods


  attribute :foo, String
end
```

I am marking this as closed because the behavior itself is working as intended.
