### ISSUE TITLE
Space/tabulation mix break the documentation

### ISSUE THREAD

**Issue by Gurdil** [lsegal/yard#868]
The third line as indent with tab unlike the other :

```ruby
        # @!method adds(array, size)
        # Addition the content of a Array
		# @param array [FFI::MemoryPointer] An array of int ##This line has indent with tab Unlike the other
        # @param size [Fixnum] The size of the array
        # @return [Fixnum] Sum of all the elements in the array
        attach_function :adds, [:pointer, :int], :int
```

The result after yardoc :
![yarddoc](https://cloud.githubusercontent.com/assets/8937083/7706405/8ca17e24-fe4a-11e4-8a6e-8789cb0374aa.png)

The description of the function become the return statement and the first argument is ignored. 

I know it's a bad thing to do, but no error is raise during yard process and it's hard to find with a daily editor.

**Comment by lsegal** [comment]
Closing out old issues. 

I am marking this as WontFix since it is too low priority. YARD is space sensitive and does not like mixing spaces and tabs. I understand that this can cause really annoying errors, but it is a fairly small edge case.

If you really want this to change and are willing to dig through the parser, I would accept a PR, provided it comes with proper testing. I unfortunately don't have time to look at this.
