### ISSUE TITLE
False-positive warns being logged

### ISSUE THREAD

**Issue by devmitchell** [lsegal/yard#885]
I'm seeing an issue where there are some false-positive warns being logged to the console when generating the documentation. This is occurring when I'm trying to take advantage of Ruby's update to the return value of `def`.

https://www.ruby-lang.org/en/news/2013/12/25/ruby-2-1-0-is-released/

Here is a spec that demonstrates the problem; I've added it to docstring_parser_spec.rb's after_parse describe block:

```ruby
it "should prevent false-positive warn about invalid named parameters when utilizing def return value" do
  log.should_not_receive(:warn).with(/@param tag has unknown parameter name: isaparam/)
  YARD.parse_string <<-eof
    ##
    # @param isaparam foo
    handle_asynchronously def foo(isaparam) end
  eof
end
```

Oddly enough, I find that it's a combination of having that second hash symbol in the first line of the method documentation and invoking a macro (such as Delayed Job's `handle_asynchronously`) in the method signature. I find no error happening when i remove that second hash character:

```ruby
it "should prevent false-positive warn about invalid named parameters when utilizing def return value" do
  log.should_not_receive(:warn).with(/@param tag has unknown parameter name: isaparam/)
  YARD.parse_string <<-eof
    #
    # @param isaparam foo
    handle_asynchronously def foo(isaparam) end
  eof
end
```

I gave a good effort of trying to find where the error might be happening, but to no avail.

**Comment by lsegal** [comment]
Using method symbol returns is a nifty little feature, but quite simply, YARD can't parse this and probably won't ever be able to without a serious rethinking of the handler architecture. You should stick to explicit declarations when documenting code:

```ruby
# This is actually a method and it's very clear to readers that it is!
def foo(isaparam) ... end

# This is a behavioral augmentation to a method and
# I am properly separating this concern from the method
# declaration itself
handle_asynchronously :foo
```

The advantage of the above is that it will work in pretty much any doc / analysis tool you throw at it, including doc tools like RDoc and Doxygen, and also you still get support from IDEs like RubyMine.

FWIW, the error in block 1 is coming from a method being defined with no parameters (because it's probably defining a method called "def"), and the second (lack of) error is coming from no method being defined at all.

**Comment by devmitchell** [comment]
I was worried about that. Can you explain this comment a bit more (just for my education)? I'm not so sure I follow that.

> ...and the second (lack of) error is coming from no method being defined at all.

Thanks in advance!

**Comment by lsegal** [comment]
> Both of the method signatures are identical, and as such I would think they'd have the same behavior.

YARD isn't parsing the `def`. All it sees is:

> **handle_asynchronously** `probably_the_method_name` *some kinda other code stuffs*

When you use two "##"s, you're activating the "metaprogrammed mode" as per [RDoc's behavior here](http://docs.seattlerb.org/rdoc/RDoc/Parser/Ruby.html), which YARD emulates. YARD then guesses at the method name by finding the first identifier, which luckily is `foo` and not `def` (since `def` is a keyword). It doesn't do any more guessing though, all it sees is a method `foo` that takes no arguments.

For what it's worth, you can work around this by providing an overload or just using the `@!method` directive:

```ruby
# @!method foo(isaparam)
#   @param isaparam foo
handle_asynchronously def foo(isaparam) end
```

Or, if you must use "##",

```ruby
##
# @overload foo(isaparam)
#   @param isaparam foo
handle_asynchronously def foo(isaparam) end
```

**Comment by devmitchell** [comment]
I love a good explanation. Thanks!
