### ISSUE TITLE
"class Full::Path::To::Constant" generates a non-hierarchical entry in the index

### ISSUE THREAD

**Issue by doudou** [lsegal/yard#892]
An image being worth 1000 words. A bunch of class definitions looking like

~~~
class OroGen::AuvControl::Base
...
~~~

Leads to the following. I would have expected to get the namespaces nicely separated in a hierarchy

![these entries in the generated index](https://cloud.githubusercontent.com/assets/292/9063505/1af75416-3a9e-11e5-96a5-9f5ae158ba5d.png)

**Comment by lsegal** [comment]
This is expected behavior if the wrapping namespaces have not been defined in your codebase. YARD only builds a hierarchy of objects that have been explicitly defined in your code. My guess is `OroGen` is probably defined externally. You could make this work if you did:

```
module OroGen
  module AuvControl
    class Base; ... end
  end
end
```

(or `class`, if that's what they are)

This would define these namespaces in your code and make it traversable in the hierarchy.

**Comment by doudou** [comment]
Alright then ... So if I understand you correctly, if I declare the modules beforehand using e.g. a yard plugin it would work alright ? Would be great to have YARD issue one more of these very helpful warnings about it ;-)

In my case, the class automatically gets created to represent some external model. I recommend using the "class FULL_PATH" syntax to make the loading fail if the ressource is not there / disappears / if there is a typo.

Thanks ! I'm closing the issue.

**Comment by lsegal** [comment]
> if I declare the modules beforehand using e.g. a yard plugin it would work alright ? 

You don't need a YARD plugin to do this, just define it in code if you want it in your class list hierarchy. You could also just add: 

```ruby
module OroGen; module AuvControl; end end
```

If you want YARD to generate these in a hierarchy.

> Would be great to have YARD issue one more of these very helpful warnings about it

There's nothing to warn about, since this is expected (and rather correct) behavior. Nothing is broken, and it's working as intended. The intention is that objects without a known module hierarchy get placed at the root of the list.

**Comment by doudou** [comment]
> You don't need a YARD plugin to do this, just define it in code if you want it in your class list hierarchy. You could also just add:

I know, but I don't want to tell my users "you have to declare this automatically-declared namespace manually, and make sure its name will always match the rest of the system, otherwise your documentation is screwed".

> There's nothing to warn about, since this is expected (and rather correct) behavior. 

I got the rationale. And I got bitten by it, because I did not realize what I was doing wrong. Which is what all the YARD warnings are great about telling us users ...

Anyways, now that I know how I can fix it, thanks again.
