### ISSUE TITLE
Symbols are incorrectly parsed as keywords

### ISSUE THREAD

**Issue by iankronquist** [lsegal/yard#896]
The symbol `:ensure` is represented as a keyword:
```
s(:symbol_literal, s(:symbol, s(:kw, "ensure", line: 84..84, source: 3424..3429), line: 84..84, source: 3423..3429), line: 84..84, source: 3423..3429), false),
```

It should be an identifier:
```
#--------------------------------\/
s(:symbol_literal, s(:symbol, s(:ident, "ensure", line: 84..84, source: 3424..3429), line: 84..84, source: 3423..3429), line: 84..84, source: 3423..3429), false),
```

**Comment by lsegal** [comment]
[Ruby's `ensure` is a keyword][1]. Also, this data is returned directly from Ripper, a.k.a., Ruby's canonical parser.

[1]: http://www.tutorialspoint.com/ruby/ruby_quick_guide.htm

**Comment by iankronquist** [comment]
Should I report this to ripper then?
I'm think that in the context of the symbol `:ensure` this should not be a keyword. Ensure may be a keyword, but this is a symbol.

**Comment by lsegal** [comment]
You could potentially do this, but changing that would be a breaking change in the library, so I don't know if it would be accepted.

It's worth noting that using `:keyword` is not technically wrong. The AST provided *does* list `:ensure` as a symbol. It simply also notes that the identifier within the symbol is actually a keyword (which it is). The child node itself is not context-dependent.

Either way, this is not an issue with YARD, it would be a third-party issue unless there's some specific YARD behavior that is broken due to this. Closing this issue unless that YARD behavior can be provided.

**Comment by iankronquist** [comment]
https://bugs.ruby-lang.org/issues/6306
Here is the bug in ruby which discussed this. It was closed. I'm with the original reporter on this one, but alas.
