### ISSUE TITLE
Case sensitivity issue with modules.

### ISSUE THREAD

**Issue by JonRowe** [lsegal/yard#906]
I'm having trouble writing tags for two modules which have similar names, namely `RSpec` and `Rspec` (note the lower case `s`). We need the latter for compatibility with Rails (see rspec/rspec.github.io#50) but our generated docs end up with same filename and overwrite each other... because this module is private I tried to label it as `@private` but this marks all the modules under `RSpec` as private too.

**Comment by lsegal** [comment]
YARD itself is case sensitive; the problem here is that your filesystem likely is not (which is completely understandable), so YARD's writing `RSpec.html` and `Rspec.html` and the FS is overwriting the other node.

A workaround for this would be to replace the file system serializer when generating documentation. It's not pretty, but it should work:

https://gist.github.com/lsegal/00968a764bc5e91e5ac2

Doesn't work on rubydoc.info, but it looks like you are generating static docs anyway, so this should be fine.

It should be possible to work the above code directly into YARD to support FS case collision mapping (with a bit of a perf cost) so I will keep this issue open to track that.

That said, bringing this back to your specific issue-- I was reading through the related ticket and I'm not seeing any good reason why you would want the compat class `Rspec` to be in your public docs. Am I missing something here? Presumably you *want* to hide it, including all of its children. I'm betting that people would be confused by seeing `RSpec` *and* `Rspec` side by side in your docs, regardless of the intent.

**Comment by JonRowe** [comment]
Yes I would like to hide it, but marking it as @private marks RSpec as
@private, this is in both output and from the server mode which doesn't
suffer from the file system issue
>
>

**Comment by lsegal** [comment]
> Yes I would like to hide it, but marking it as @private marks RSpec as @private

Marking `Rspec` as private should *not* mark `RSpec` as private as well. The following generates an RSpec.html:

```ruby
module RSpec; end

# @private
module Rspec; end
```

Can you show a reproduction case for that? That sounds like a different issue.

**Comment by JonRowe** [comment]
rspec/rspec-rails#1479 shows this

**Comment by lsegal** [comment]
Can you show a minimal case, or some code? It's hard to understand how all of that is wired up under the screenshot. Unless RSpec is under Rspec, these should not be associated in any way by YARD (as mentioned, YARD is case sensitive when it comes to paths in memory).

**Comment by JonRowe** [comment]
Rspec is not under RSpec in anyway, and the files mentioning Rspec do not define RSpec.

**Comment by lsegal** [comment]
The original issue being reported here should now be resolved. You should be able to generate `RSpec` and `Rspec` modules side-by-side if running against master.

**Comment by JonRowe** [comment]
Thanks, I think the other issue is actually a non-issue, I think some of our classes are labeled badly (we generally consider instantiating classes to be private but some of their api is considered public, weird I know)
