### ISSUE TITLE
rb_define_class_under gets no documentation

### ISSUE THREAD

**Issue by thomthom** [lsegal/yard#914]
Not sure if this is intended or not but, `rb_define_class` pick up the comment from the function comment:

```
// Hello Foo World.
void Init_Foo() {
  g_rbFoo = rb_define_class("Foo", rb_cObject);

  rb_define_method(g_rbFoo, "world", VALUEFUNC(_wrap_world) , 0);
  rb_define_method(g_rbFoo, "hello", VALUEFUNC(_wrap_hello), 0);
}
```

But `rb_define_class_under` doesn't:

```
// Hello Baz World.
void Init_Baz() {
  // What about this?
  g_rbBaz = rb_define_class_under(g_rbBiz, "Baz", rb_cObject);

  rb_define_method(g_rbBaz, "world", VALUEFUNC(_wrap_world), 0);
  rb_define_method(g_rbBaz, "hello", VALUEFUNC(_wrap_hello), 0);
}
```

No class documentation is added for the `Baz` class.

If I add `Document-Class` to the comment it will work, but it would be nice to not have to retype the class name.

Repro gist: https://gist.github.com/thomthom/ee0a29efbe150491e1c4

**Comment by thomthom** [comment]
`rb_define_module` also appear to not pick up the comment for the C function that defines it.

**Comment by lsegal** [comment]
Adding comments to the `Init_*` method should not apply to classes defined within the body-- that's the "bug" here. I don't think there's ever been any explicit support for inline documentation of classes, that seems to be a side-effect of the parser, not a feature. In other words, you should be using `Document-class: Foo` in ALL cases. Any other usage is effectively *undefined*.

To be clear: support for documenting C code alongside Ruby APIs is currently defined by the conventions used in the Ruby core codebase, and is specifically designed to work with that codebase (specifically in order to document the stdlib). You should follow the conventions that Ruby uses to document things for best results. See [win32ole_error.c](https://github.com/ruby/ruby/blob/832c74f428db6c5bd6e575e1f6ea7fe0891c84d2/ext/win32ole/win32ole_error.c) or [tcpsocket.c](https://github.com/ruby/ruby/blob/33f3789e852080cc6b681748f56bd29f7a555b22/ext/socket/tcpsocket.c) as examples of how Ruby does this.

Improvements could be made to the parser based on pull requests, but as of now, the syntax you are using is not supported.

**Comment by thomthom** [comment]
Ok, I can work with that. My only presumption for that to work was from the test spec:
https://github.com/lsegal/yard/blob/master/spec/handlers/c/init_handler_spec.rb#L11

Thinking of it closer, using `Document-class/module` is probably more flexible - as init functions might define multiple classes.

Thanks for clarifying.
