### ISSUE TITLE
@!attribute reports some custom writers containing `fail` as undocumented, but not `raise`

### ISSUE THREAD

**Issue by dmolesUC3** [lsegal/yard#921]
Investigating #920, I found a significantly weirder case. Given the following (using [XML::Mapping](http://multi-io.github.io/xml-mapping/)) --

```ruby
require 'xml/mapping'

# XML mapper with custom writer
class Xml
  include XML::Mapping

  # @!attribute [rw] foo
  #   @return [String] the foo value. Cannot be nil.
  text_node :foo, 'foo'

  alias_method :_foo=, :foo=
  private :_foo=

  def foo=(value)
    raise ArgumentError unless value
    self._foo = value
  end
end
```

-- YARD correctly reports the class as fully documented. However, if I change the `raise` in `foo=` to a `fail` (as recommended by RuboCop) --

```ruby
require 'xml/mapping'

# XML mapper with custom writer
class Xml
  include XML::Mapping

  # @!attribute [rw] foo
  #   @return [String] the foo value. Cannot be nil.
  text_node :foo, 'foo'

  alias_method :_foo=, :foo=
  private :_foo=

  def foo=(value)
    fail ArgumentError unless value
    self._foo = value
  end
end
```

-- I get:

```
Undocumented Objects:

(in file: xml.rb)
Attribs::Xml#foo=
```

This is not affected by whether the `raise`/`fail` call includes a string message.

**Comment by lsegal** [comment]
YARD autogenerates tags when it detects `raise` in a method body, therefore, in any case where `raise` is found, there is documentation associated with the method. It has no knowledge of `fail`, however, since `fail` is a method and can't reliably be tracked the same reliable way a keyword can. This is also expected behavior.

I have no idea why the Ruby style guide. Both are equivalent, but one is a keyword, which means it's not only faster (no method dispatch overhead), but it also can't be accidentally overridden. I've never seen wide use of `fail` outside of short CLI-based Ruby scripting usage. Using `raise` seems like a much more accepted convention to me, but that's neither here nor there, I suppose.
