### ISSUE TITLE
Nested namespace references in constants C comments mangled.

### ISSUE THREAD

**Issue by thomthom** [lsegal/yard#928]
I haven't been able to track down why this happens, but this is my test snippet:

```
void Init_Baz() {
  g_rbBiz = rb_define_class("Biz", rb_cObject);
  g_rbBaz = rb_define_class_under(g_rbBiz, "Baz", rb_cObject);
}


void InitRubyRenderingOptionsClass() {
  g_rbThing = rb_define_class("Thing", rb_cObject);

  // Hello World
  rb_define_const(g_rbThing, "HelloWorld", Qnil);

  // These constants are used by {Biz::Baz}.
  rb_define_const(g_rbThing, "LoremIpsum", Qnil);

  // These constants are used by Biz::Baz.
  rb_define_const(g_rbThing, "FooBar", Qnil);

  // These constants are used by {Biz}.
  rb_define_const(g_rbThing, "PingPong", Qnil);

  // These constants are used by Biz.
  rb_define_const(g_rbThing, "Orange", Qnil);
}
```

This is the result I see:
![2016-01-07_15h31_07](https://cloud.githubusercontent.com/assets/192418/12172844/b6932d02-b553-11e5-8447-2160cffd351d.png)

I'm guessing `parser/c/comment_parser.rb` is where to start looking for this?

**Comment by lsegal** [comment]
That's because the CRuby formatting for constants (inherited by RDoc's style) is:

```
/**
 * CONSTVALUE: docstring
 */
```

And YARD is matching the `:` and parsing as such. Unfortunately if you're going to use reference linking inside of a CRuby const docstring, you will have to prefix it with an explicit `VALUE:` prefix.

You can see more examples in RDoc's tests here: https://github.com/ruby/ruby/blob/3e92b635fb5422207b7bbdc924e292e51e21f040/test/rdoc/test_rdoc_parser_c.rb#L400-L421

Note that you probably *want* to be using an explicit `VALUE:` prefix, otherwise the constants will not document any values, since they are *not* pulled out automatically from the `rb_define_const` line.

**Comment by thomthom** [comment]
Ah - it splits it after the first `:`. That makes sense now. I wasn't seeing what YARD did to the first part because in my template I had modified it to not display the constant value. We didn't want to document that because they are implementation details of magic numbers that might change - and we want our API users to use the constant names instead of the actually value they might be in any particular release.

There was also the issue that the C code didn't show what value it would be. But this syntax now gives us that option. Thanks for clarifying that.

**Comment by thomthom** [comment]
Is it possible to associate a constant with a @version tag in this format?

**Comment by lsegal** [comment]
The short answer is no, tags do not support constant interpolation. The longer answer is that you can write a directive to add the right version. 

Keep in mind, however, that the `@version` tag may not mean what you want it to mean. Typically a version for a component implies that it rolls independently of your library version, otherwise you probably don't want to be using this tag at all. Docs [are here](http://www.rubydoc.info/gems/yard/file/docs/Tags.md#version).

**Comment by thomthom** [comment]
We use version to indicate with what version of our software the API feature was added. Up til now we haven't had much documentation for constants. But I was looking into improving that.

After some tinkering with different formatting for the comments I found that I could do this to have constants documented with a description and version tag:

```
  /* 0: {Sketchup::Entities#fill_from_mesh} No smoothing or hiding of edges.
   * @version SketchUp 2014
   */
```

That added the version tag to the constant. Though I might massage the template to how it's presented. But in addition to documenting when the constant became available I can now use YARD to query and filter constants by versions :)
