### ISSUE TITLE
1.0 release for semantic versioning

### ISSUE THREAD

**Issue by ioquatix** [lsegal/yard#931]
It would be awesome to have a 1.0 release (http://semver.org). Thanks for your awesome software.

**Comment by lsegal** [comment]
Although I understand the request, there isn't much of an actionable item for this issue. A 1.0 release will come when a 1.0 release is warranted, and right now it is not.

YARD pre-dates SemVer, and has been effectively "stable" since its inception 8 years ago. The project tries its hardest to achieve backward compatibility between releases. That said, whether you follow SemVer or not (technically speaking YARD does not use SemVer), the 0.x vs. 1.x issue isn't all that relevant here. If you'd like to, you can interpret YARD's current state as "unstable" from an API compatibility perspective. It's not technically the case, but practically speaking, it doesn't change very much.

The only important semantic is this: YARD *will* bump the major version if an unforeseeable major breaking change is necessary, at which point there will be a 1.x release.

**Comment by ioquatix** [comment]
You might want to add this to the README, I couldn't find it when I looked, and it sounds like this is a policy of the project? Perhaps explaining the versioning system would be great, as when I initially looked at it, I thought it was still an unstable release.

**Comment by lsegal** [comment]
I'm not sure that spending time explaining YARD's versioning scheme in the already-long-README would be all that useful, nor would it actually answer the question that I think you're really asking:

"Is YARD stable enough to use in 'production'?" 

The answer is yes, and this answer needs no explanation of the versioning scheme. 

I would typically only expect *unstable* libraries to call out their instability in a README, not the other way around. Even 0.x products that follow SemVer will (or should) mention that they are in development stages if they are not actually production-ready, since API compatibility and production-readiness are two very different things (Node being a wonderful example of this). In this case, since the product is stable, there's no real need to call that out (it should be implied, especially with an 8 year old project).

Though I'm wondering: are you referring to the stability of the API in particular, or the stability of YARD as a program in general?

**Comment by ioquatix** [comment]
For me, the definition of API is pretty broad. To answer your question, I guess I'd like to confirm the stability of the API. Guaranteeing program stability isn't something easy to do. For example, EventMachine 1.0.x crashes with some usage of IPv6 which was not really common when it was originally released. Personally, I'd like to see instability fixed in ALL releases as soon as possible.

For me, a 1.0 release indicates that the product has reached a certain level of maturity. That's hard to define but SemVer is a pretty decent guideline.

**Comment by ioquatix** [comment]
> it should be implied, especially with an 8 year old project

This isn't really obvious from a casual glance. Also, just based on my experience, age doesn't really correspond with quality/stability/unreliability, etc. A single linear version can't really do it all justice :)

**Comment by lsegal** [comment]
> For me, a 1.0 release indicates that the product has reached a certain level of maturity

But this is not the actual intent of the version number. SemVer does not police project maturity, only API stability, in a pretty narrow sense, too. A project does not need to be mature to get a 1.0, it simply has to have a "locked API" for the duration of the 1.x releases, which itself isn't really a guarantee of much. There are plenty of projects that get a 1.0 within a few weeks of release only to end up going to 2.0 in a few more months to fix all the mistakes of the original 1.0 version lock.

On the other hand, YARD is on the same major version that it started with 8 years ago. That should tell you quite a bit about how stable and mature the API is.

**Comment by ioquatix** [comment]
When I see "0.8" I immediately thing that the project hasn't released a stable 1.x release. I'm sorry, but that's just the initial impression I got. In my experience, it's pretty canonical to have a 1.0 release once things stabilise and mature. You are welcome to your opinion and I respect that and you've obviously put in the effort. SerVer is at least a baseline for what x.y.z means.

> There are plenty of projects that get a 1.0 within a few weeks of release only to end up going to 2.0 in a few more months to fix all the mistakes of the original 1.0 version lock.

In one project, we have done exactly what you said due to required breaking API changes which were developed in quick succession from a major bug fix release. I wouldn't call it "fixing all the mistakes" but rather just a specific path that we needed to take to move things forward.
