### ISSUE TITLE
Connected C comments (`//`) aren't recognized

### ISSUE THREAD

**Issue by boazsegev** [lsegal/yard#940]
First of all - thank's for an amazing documentation tool.

I'm writing a C extension for Ruby and noticed that C++ style comments in C aren't recognized when running through multilines.

i.e.

```c
// this is a description
// for a method
VALUE func(VALUE self)
{
}
```

The documentation will show only "`for a method`"

Whereas:

```c
/* this is a description
 for a method */
VALUE func(VALUE self)
{
}
```

The documentation will correctly evaluate.

Since the C++ style commenting notation (`//`) is so prevalent in different IDEs, it's easier to comment documentation using `//` then `/* ... */`.

Could this issue with multi-line C++ style comments be resolved?

**Comment by lsegal** [comment]
Unfortunately there are no plans to support multi-line single-line comments in the CRuby parser. The CRuby parser is primarily meant for legacy support of Ruby's core API, which means we only target parity with what RDoc provides. At the very least, we are more strict about the supported documentation styles in C land due to the primary focus of YARD being about Ruby code.

You should use multiline C comments when documenting C code with YARD. It is the convention for documenting CRuby code.

**Comment by lsegal** [comment]
Marking this issue as closed and labeling WontFix *for now*. I want to point out that I'm not -1 on this, but given the nature of CRuby support, the complexity of implementing this, and the easy (and more portable) workaround, I don't see this getting added to YARD unless something changes in the aforementioned calculus.

Thank you for bringing this up though, and hopefully using `/**/` is a sufficient solution!

**Comment by boazsegev** [comment]
Hi Loren,

Thanks for the info, the consideration and the great yard gem. Prioritization is super important, so I totally relate to the approach.

Good luck!
