### ISSUE TITLE
Quotes in inline code is tranformed

### ISSUE THREAD

**Issue by thomthom** [lsegal/yard#949]
If I write something like this trying to quote a string literal:

```
Some +"Hello String"+ text.
```

...the quotes get transformed:

> Some `“Hello String”` text.

This was not something I expect to happen. Is this intended?

**Comment by lsegal** [comment]
YARD defers all markup conversion to the markup libraries. That is likely a behavior of RDoc's markup conversion to HTML.

**Comment by thomthom** [comment]
Gotcha. I'll poke around there then. 

Having said that... maybe I should try markdown. Since we're using markdown for the other auxilirary docs.

**Comment by lsegal** [comment]
I should add one thing here-- RDoc by default does not (or did not, historically) support using `+foo+` when there are spaces in "foo". YARD adds a tiny little hack to the RDoc parsing to support `+foo bar+`, and it may be that due to the order-of-events, RDoc is treating `foo bar` as prose and not code, thereby converting quotes. You could test this with `+"Hello"+`. The RDoc way to do support spaces would be to use the long-form `<tt>"Hello String"</tt>`, I believe, unless that's changed recently.

**Comment by thomthom** [comment]
When I ran into this I didn't have space in my string. I had stuff like `“.”`, `“-”` and `“_”` - just a single quoted character. But I'll look closer at RDoc formatting again - I jumped straight to YARD so I'm not that familiar with RDoc. Thanks for the follow-up.

**Comment by lsegal** [comment]
Closing this since this issue is related to the markup library being used. Note that you can use Markdown (`-m markdown`) which would provide much more consistent (and powerful) formatting rules to RDoc's.
