### ISSUE TITLE
Kramdown in YARD, generated HTML is treated as text to display in some cases.

### ISSUE THREAD

**Issue by aef** [lsegal/yard#965]
When using [kramdown](https://github.com/gettalong/kramdown/) with YARD, when using blocks surrounded with `~~~~~`, I get fixed-width code blocks. However, when I use `~~~~~ ruby` as the starting line, it seems the same markup is generated, but it is then escaped, so that I see a bunch of HTML tags in the generated documentation.

Is there anything I am doing wrong? Why is this happening?

I am using `kramdown` gem version 1.11.1 with the `yard` gem version 0.8.7.6. Ruby version is MRI 2.3.0p0.

I used the following to configure YARD:

~~~~~
--output-dir=doc/api
--embed-mixins
--protected
--no-private
--markup-provider=kramdown
--markup=markdown
-
HISTORY.md
LICENSE.md
~~~~~

Generate the documentation for [my file_permissions gem](https://github.com/godobject/file_permissions) to get an example of the problem.

I brought this issue up with [kramdown](https://github.com/gettalong/kramdown/issues/337), but they directed me to bring this up with YARD.

**Comment by lsegal** [comment]
You likely have `coderay` (or another syntax highlighting gem) installed, which apparently kramdown automatically uses when available.. One workaround would be to use `--no-highlight` in YARD to let kramdown use its own highlighting. That does seem to cause other issues though, and might look weird since it does not rely on css styles for color selection. Those are fixable things, with extra customization, though. There is no current way to disable highlighting on Kramdown generated HTML in YARD, since it's on by default (it did not used to be). YARD would have to be updated to be able to [reach into Kramdown and disable highlighting](http://kramdown.gettalong.org/options.html#option-syntax-highlighter), though I'm not sure if that's really what you want to do. At the very least, you could disable line numbers so CSS customizations would not be needed-- patches could be accepted for this, [here's where to look](https://github.com/lsegal/yard/blob/master/lib/yard/templates/helpers/html_helper.rb#L58).

Another solution would be to run YARD in the context of a bundler environment where only yard and kramdown are active (create a separate Gemfile or group with only yard and kramdown and bundle exec that). This still has an issue where Kramdown seems to use `language-X` as the class name, which YARD does not (yet) recognize, so it will go from garbled HTML to unhighlighted code. Unhighlighted is better, but probably not ideal. Patches (w/ tests) accepted [to fix this one](https://github.com/lsegal/yard/blob/master/lib/yard/templates/helpers/html_helper.rb#L586).

Alternatively, you could use another Markdown library, given that you will still be left with the className issue. `rdiscount` is the default and seems to generally get the best results / be the most consistent, but it is a native gem. You could also try `rdoc` as the Markdown markup provider. I know that sounds confusing-- to be clear, you would still use Markdown, but the rdoc gem now supports parsing Markdown, and YARD can use this provider. You would have to change your `~~~~ ruby` fences to the Github style of <code>``` ruby</code> (but you would have to do this with rdiscount too). I tested rdoc and it worked on your repo for me.

Hope that helps!

**Comment by lsegal** [comment]
Closing out old issues.
