### ISSUE TITLE
Documenting param having a recursive type.

### ISSUE THREAD

**Issue by faucct** [lsegal/yard#982]
Hello, can you tell me if there is a way to document the param of a recursive type, like in `ActiveRecord::Base.includes(*args)`? Those are the examples of `args`:

```ruby
[:children]
[children: []]
[children: [grandchildren: [:grandchildren, children: []]]]
```

**Comment by lsegal** [comment]
This isn't really a recursive type so much as a recursive literal / Array specifically. An actual recursive type like a Node class would have a proper tree structure through attributes or something more documentable (like a #children method). In that scenario, you could document Node as the type where each node has its own children structures documented on the class.

In your case, the type is restrictive in that it inherently lacks structure with which to document. You may want to consider this as a design issue with your API. You may be stuck with it (I can't tell if AR is an example or the actual API), but if not, you may want to consider adjusting the API to be more doc-friendly. Creating real structure for your type would make it more documentable.

That said, YARD's type specifiers are free-form text, so you could really write whatever you like to properly declare the type specification for that parameter. There is no syntax recommendation for recursive types because they don't come up enough to have made a recommendation for it. You could make one of your own, like:

```
@param args [Array<Symbol, Array<Symbol, Array<...>>>] docs here
# shorthand:
@param args [<Symbol, <Symbol, <...>>>] docs here
```

Or

```
@param args [RecursiveArray<Symbol, RecursiveArray>] docs here, explain `RecursiveArray` as recursive type here.
```

At the end of the day, the type specifier won't matter for a structureless type-- using `@example` tags will be much more clarifying.

Hope that helps.
