### ISSUE TITLE
YARD autoload.rb comments - small issue

### ISSUE THREAD

**Issue by MSP-Greg** [lsegal/yard#998]
autoload.rb has several comment strings attached to NS objects.  This causes the main file shown in 'Defined in:' to be autoload.rb.  See --

http://www.rubydoc.info/github/lsegal/yard/YARD/CodeObjects

The CodeObjects module has most of its properties defined in the codeobjects/base.rb file.  Same situation for several other objects.  I would think the main file should be codeobjects/base.rb

I have moved several of the comments (with no changes) out of autoload.rb and into other files more related to the objects.

You may prefer it as is.  I can revert these changes or create a pull request.

This leads to another question re YARD functionality, which I have never seen mention of, and which is included in RDoc.  Should there be an means to exclude a comment from documentation?  Using the current examples, main comments to be attached to 'base.rb' files, but one could also have comments attached to the same object in the autoload.rb file.

I have read the [Contributing Guide][contrib].

**Comment by lsegal** [comment]
The autoload file is indeed where those objects are defined and documented. I don't see a bug here. 

More importantly, though, removing the comments won't change the "Defined in" section, since that's not related to docstrings, but rather where the object has been detected as defined in source. for classes/modules, that's every time they are re-opened. The `lib/autoload.rb` file will show up regardless. The order that the file shows up in depends on the order that files are parsed, but it will at the very least always be in the list somewhere.

> This leads to another question re YARD functionality, which I have never seen mention of, and which is included in RDoc. Should there be an means to exclude a comment from documentation? Using the current examples, main comments to be attached to 'base.rb' files, but one could also have comments attached to the same object in the autoload.rb file.

This is not exactly relevant because of the above explanation, but #625 has brought this up before. There aren't really any plans to support toggling of comment parsing like in RDoc because it's simply not needed.

**Comment by MSP-Greg** [comment]
> The order that the file shows up in depends on the order that files are parsed, but it will at the very least > always be in the list somewhere.

I believe the 1st file shown in 'Defined in:' depends on which files have comments.  Hence, if comments are moved from autoload.rb to another file that does not have comments, the 2nd file will be listed first.

To clarify, moving the comments may change which file is listed first in 'Defined in:', but the list will still contain the same file list.

Regardless, I remove the changes.

**Comment by lsegal** [comment]
Sure. In this case the module is in fact defined primarily in the autoload.rb file. The base.rb file is for the CodeObjects::Base class. Other stuff has leaked into that file over time, but all toplevel modules are defined and documented in autoload.rb per convention.
